### ISSUE TITLE
Drop-in UI is not translated

### ISSUE THREAD

**Issue by namanhams** [braintree/braintree-android-drop-in#1]
We have been using Drop-in UI in our app for quite a long time. It works very well. The only thing is that we just notice recently that it's not localized. We change device language to Chinese, Japanese, .... but the drop-in is still in English.

This is how we integrate Braintree in our Gradle file 
`compile 'com.braintreepayments.api:braintree:2.+'
    compile 'com.braintreepayments.api:drop-in:2.+'
    compile 'com.braintreepayments.api:data-collector:2.+'`

**Comment by lkorth** [comment]
Version 2 of Drop-in is only localized in 17 languages, you can find the languages it currently includes in the [`res` folder](https://github.com/braintree/braintree-android-drop-in/tree/daacdd06c12c77cb27b92c646a55792da0ddbc6b/Drop-In/src/main/res).

In the future we plan on adding more languages to Drop-in.
