### ISSUE TITLE
disableAndroidPay() ignored 

### ISSUE THREAD

**Issue by bblackbelt** [braintree/braintree-android-drop-in#10]
Hi Guys, the disableAndroidPay() flag seems to be ignored. The option is still showed in the Drop-in. Furthermore the method isAndroidPayEnabled is never called in the DropInActivity. 

Please advise

**Comment by quinnjn** [comment]
@bblackbelt thank you for the report! We'll work on a solution for this.

**Comment by quinnjn** [comment]
Fixed in 651bee260eac3af47260c09038df3404519667b5

Thanks again for the PR!

**Comment by bblackbelt** [comment]
@quinnjn thanks for let me help!
