### ISSUE TITLE
Credit Card Option Not Showing

### ISSUE THREAD

**Issue by priyan8783** [braintree/braintree-android-drop-in#102]
I am using the latest version for Drop-In UI of Braintree Android SDK, however, Drop-In is not showing credit card/debit card option. It is only showing Paypal option.

**Comment by hollabaq86** [comment]
Hi @priyan8783, can you [Braintree Support](https://help.braintreepayments.com)? That will be the best way for us to help troubleshoot your issue.

**Comment by kishanbharda** [comment]
@priyan8783 have you found any solution ? I have same problem.
