### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by codesunshine** [braintree/braintree-android-drop-in#104]
Android 7.1.2, AddCardActivity is Black screen.
log is:
11-15 20:27:08.765 4052-4059/? E/ion: ioctl c0204900 failed with code -1: Out of memory

**Comment by quinnjn** [comment]
Would you be able to provide the stacktrace when you get this exception?

What device are you using when getting this exception?

**Comment by quinnjn** [comment]
I'm going to close this due to inactivity. Comment with a stacktrace if this is still an issue and we'll reopen the issue.
