### ISSUE TITLE
Error with Drop SDK

### ISSUE THREAD

**Issue by Bikcodeh** [braintree/braintree-android-drop-in#106]
I want to use this in my project 

implementation 'com.braintreepayments.api:drop-in:3.7.1'

But my project is with SDK 26, so when I put it in my Gradle and then I do Sync I get this:

Process 'command 'C:\Users\***\AppData\Local\Android\Sdk\build-tools\26.0.2\aapt.exe'' finished with non-zero exit value 1

I don't know hot to fix it, help me please.

When I use SDK 28 works fine, but with 26 not.

**Comment by quinnjn** [comment]
I believe you'd want to target and compile to the latest Android SDK as [suggested by Ian Lake](https://medium.com/androiddevelopers/picking-your-compilesdkversion-minsdkversion-targetsdkversion-a098a0341ebd)
```
compileSdkVersion 28
targetSdkVersion 28
minSdkVersion <your choice>
```

Once you update those values, you can use `drop-in:3.7.+`

In `drop-in:3.7.0` we made a change that was [preventing SDK 28 from building](https://github.com/braintree/braintree-android-drop-in/issues/77) and this looks like a consequence of that.

If it is not possible for you to upgrade your SDK versions at this time, you can stick with `drop-in:3.6.+`
