### ISSUE TITLE
What happens with 3D-Secure 2.0

### ISSUE THREAD

**Issue by achalkias** [braintree/braintree-android-drop-in#110]
I use DropIn-UI in many apps.
Today I received an email that said that I have to integrate 3d secure 2.0 to my apps. I don't currently have 3d secure in my  DropIn-UI enabled.

So what I have to do?
Is the 3D Secure 2.0 ready for drop in ui in android? If not when will it be?
Thank you in advance. I hope you can help me figure this out.

**Comment by hollabaq86** [comment]
Please contact [Braintree Support](https://help.braintreepayments.com/) referencing this issue, they're the best team to answer your questions.
