### ISSUE TITLE
Adding email field to Drop-in UI on Android

### ISSUE THREAD

**Issue by osawyerr** [braintree/braintree-android-drop-in#115]
### General information

* SDK/Library version: com.braintreepayments.api:braintree:2.+
* Environment: Sandbox
* Android Version and Device: Note 9

### Issue description

Is it possible to add an email field to then Drop-in form? I haven't figured out how to do this and it seems like a strange omission if its not possible! i.e. If we are not allowed to capture this how does one send confirmation emails to users?

**Comment by crookedneighbor** [comment]
For now, you can collect email _outside_ of Drop-in.

Collecting email from within Drop-in is on our roadmap, but not available yet.

**Comment by scannillo** [comment]
Closing this ticket as it no longer on our roadmap. 

Feel free to re-comment on this issue, open a new one, or reach out to [Braintree Developer Support](https://developer.paypal.com/braintree/help) if the need for adding an email field arises.

**Comment by osawyerr** [comment]
Only 4 years late! lol
