### ISSUE TITLE
logout is not possible on production

### ISSUE THREAD

**Issue by radhikapooniya2** [braintree/braintree-android-drop-in#121]
### General information

* SDK/Library version: 
* Environment: 
* Android Version and Device:

**Comment by radhikapooniya2** [comment]
on braintree production always showing same login , logout is not possible

**Comment by scannillo** [comment]
Hello. This seems to be a problem logging into your Control Panel and not an issue with your integration with our android drop in UI. Please fill out a form with our support team https://help.braintreepayments.com/. 

If you are having an issue with our android drop in UI, feel free to open a new issue describing the problems you have.
