### ISSUE TITLE
BraintreeBrowserSwitchActivity missing 

### ISSUE THREAD

**Issue by dalichand123** [braintree/braintree-android-drop-in#125]
### General information

* SDK/Library version: 
* Environment: 
* Android Version and Device:

**Comment by dalichand123** [comment]
incorrectly configured in AndroidManifest.xml or another app defines

**Comment by quinnjn** [comment]
You need to declare BraintreeBrowserSwitchActivity in your Android Manifest. See step 3: https://developers.braintreepayments.com/guides/paypal/client-side/android/v3

**Comment by Seanmclem** [comment]
> You need to declare BraintreeBrowserSwitchActivity in your Android Manifest. See step 3: https://developers.braintreepayments.com/guides/paypal/client-side/android/v3

This link no longer contains any mention of `BraintreeBrowserSwitchActivity`

**Comment by sarahkoop** [comment]
Hi @Seanmclem thanks for bringing that up - we are working on fixing some broken documentation links. In the meantime, [this link](https://developer.paypal.com/braintree/docs/guides/client-sdk/setup/android/v3#browser-switch-setup) should provide the information for declaring `BraintreeBrowserSwitchActivity` in your manifest
