### ISSUE TITLE
Permission for UI change

### ISSUE THREAD

**Issue by imfullstackdeveloper** [braintree/braintree-android-drop-in#128]
I really don't have a wide knowledge of Github and how its procedures working around. I just want to make some UI changes for drop-in, so can I clone and edit the source code and adding as my own library will fine? I want to mention that I'm using this for educational purpose, not for commercial use. Thank you.

**Comment by quinnjn** [comment]
Depends on the UI change. A lot of the UI can be tweaked by overriding any of the res properties. Think CSS for Android. If you Google it, there are examples on how to do this out there.

Otherwise yes your suggestion works as well, but it might be harder for you to update drop-in in the future

**Comment by imfullstackdeveloper** [comment]
Thank you.
