### ISSUE TITLE
Transaction is completed but return false. Why?

### ISSUE THREAD

**Issue by imfullstackdeveloper** [braintree/braintree-android-drop-in#129]
I use the PayPal method to complete my transaction, everything is fine but finally, it returns me a false. I dont know why. But all the transaction perfectly showing in my dashboard.

    @PostMapping("/Checkout")
    public String checkout(@RequestParam("amount") String amount, @RequestParam("nonce") String nonce) {
        TransactionRequest transactionRequest = new TransactionRequest()
                .amount(new BigDecimal(amount))
                .paymentMethodNonce(nonce)
                .options()
                .submitForSettlement(true)
                .done();

        Result<Transaction> transactionResult = braintreeGateway.transaction().sale(transactionRequest);

        if (transactionResult.isSuccess()) {
            return "Successfull";
        } else {
            return "Failed";
        }
    }

**Comment by scannillo** [comment]
Hi @imfullstackdeveloper . This question seems like something best suited for our support team. Contact them at https://help.braintreepayments.com/ and they will walk through your integration with you to figure out where the problem is!
