### ISSUE TITLE
Paypal sandbox webview loading continuous.

### ISSUE THREAD

**Issue by AmitPrajapati1902** [braintree/braintree-android-drop-in#131]
I'm trying to integrate payment with paypal. once i am click on paypal option in popup it alway loading continuous. Nothing happen event after long wait.        

Here is the below code i'm using it. I have successfully get clientToken that i am use here.

      DropInRequest dropInRequest = new DropInRequest()
                        .clientToken(clientToken);

       startActivityForResult(dropInRequest.getIntent(MainActivity.this), REQUEST_CODE);
![Screenshot_20190514-172757](https://user-images.githubusercontent.com/4670121/57697052-faa3d880-766f-11e9-966f-e6e5009beb6a.png)

**Comment by scannillo** [comment]
Hello @AmitPrajapati1902 . Did you properly set up adding an intent filter to your AndroidManifest.xml? See the [setup guide here](https://developers.braintreepayments.com/guides/client-sdk/setup/android/v2/#browser-switch-setup). 

Can you give us some more details so we can replicate this issue? Which version of our SDK are you using?

**Comment by AmitPrajapati1902** [comment]
@scannillo  Thanks for your quick response. 
I guess its server side issue or paypal sandbox is down that time, but right now its working perfect.
But yet i'm not clear about what actually problem is. Does paypal take time to review that app i created in it. Because after 3 days it try and its working well.

**Comment by scannillo** [comment]
It was an issue with PayPal sandbox being down, but shortly after your reporting this issue PayPal got the flow up and running again. The PayPal integration doesn't take time to review the app that you created.

We will continue to follow up with PayPal on why this happened but the issue is resolved.
