### ISSUE TITLE
3D Secure not working anymore in Sandbox

### ISSUE THREAD

**Issue by quiro91** [braintree/braintree-android-drop-in#132]
### General information

* SDK/Library version: 4.7.1
* Environment: Sandbox
* Any

### Issue description

We are implementing 3D Secure and it was working fine few days ago. To pay with credit card we're using the `AddCardActivity` and passing in the `DropInRequest` the amount and true for request3d. Now all of a sudden it stopped working, because during the verification the acs url is null (using card 4000 0000 0000 0000). Did anything change on your side to cause this behaviour? I wanted to test the authentication flow in the Sandbox but now it doesn't seem to be possible anymore.

**Comment by hollabaq86** [comment]
Hi @quiro91 please [contact Braintree Support](https://help.braintreepayments.com/) referencing this issue, they will be able to provide assistance.

**Comment by demerino** [comment]
@quiro91 Are you still seeing this issue? We're unable to reproduce it at this time.
