### ISSUE TITLE
GooglePay: 

### ISSUE THREAD

**Issue by xiaoxiaohua333** [braintree/braintree-android-drop-in#133]
### General information

* SDK/Library version:   https://github.com/braintree/braintree-android-drop-in
* Environment:  Sandbox  
* Android Version and Device:  Pixel with Android 9.0

### Issue description

I run your Demo project, but it can't showing the Google Pay option in the drop-in UI by Pixel. successfully showing by emulator .

I have installed GooglePay APP and pay successfully by Google play.

**Comment by scannillo** [comment]
Hello! I just ran our latest version of braintree-android-drop-in on the Pixel 2 emulator. I do indeed see the Google Pay option properly configured in our demo app.

Are you using the latest version of braintree-android-drop-in?

![Example](https://user-images.githubusercontent.com/35243507/58711788-caa14880-8384-11e9-98a5-5c2d3de05a99.png)

**Comment by xiaoxiaohua333** [comment]
It's not emulator, the real machine (Pixel android 9

![photo_2019-06-03_13-03-42](https://user-images.githubusercontent.com/9317990/58777314-4b1fad80-8600-11e9-8fb6-01b506d5a831.jpg)

**Comment by scannillo** [comment]
I don't have a Pixel device to test on, but running the demo app on a Huawei Nexus 6P properly shows the GooglePay payment option.

Lets try to see which part of the[ `isReadyToPay` function here ](https://github.com/braintree/braintree-android-google-payment/blob/5ff94cdaa23518cfee730f249d21df19f7cc253c/GooglePayment/src/main/java/com/braintreepayments/api/GooglePayment.java#L78) is returning false.

Two things we can check:
- Is the device running on a supported Android system version? Is a supported version of Google Play services installed?
- What country are you in? Let's check if Google Pay API has launched in the your country.

**Comment by xiaoxiaohua333** [comment]
yea, I'm in China now ,but my google play account bound on US.

My device support Google pay and I often pay play with google pay.

scannillo <notifications@github.com> 于 2019年6月3日周一 下午10:53写道：

**Comment by mattaojie** [comment]
I run the demo on Nexus 6P, and it does not show the GooglePay option. Does this mean that we can't test Google Pay in China?
![1](https://user-images.githubusercontent.com/21698105/62590435-ee41bb80-b8fe-11e9-9472-10a03371809d.png)
![2](https://user-images.githubusercontent.com/21698105/62590436-ee41bb80-b8fe-11e9-8580-02ab727c7a88.png)

**Comment by hollabaq86** [comment]
Hi @mattaojie, Google Pay is [limited to certain countries](https://support.google.com/pay/answer/9023773), including in testing. In checking their documentation, it looks like Google Pay is supported in Hong Kong but not China.

When troubleshooting why Google Pay is not available, we recommend checking that you're testing in a supported [region](https://support.google.com/pay/answer/9023773), using a supported [device](https://support.google.com/pay/answer/7643995?hl=en), [browser](https://developers.google.com/pay/api/web/guides/setup#get-started), and testing with a [supported card](https://articles.braintreepayments.com/guides/payment-methods/google-pay#availability) (for more information on Google Pay availability, please see our [support doc](https://articles.braintreepayments.com/guides/payment-methods/google-pay)). 

If you continue to encounter issues testing in Google Pay, please [contact Support](https://help.braintreepayments.com/).

Finally, I'm also going to leave feedback with our Docs team to clarify our developer docs making these requirements for testing Google Pay more clear.
