### ISSUE TITLE
BUG: DropInActivity missing super call to onActivityResult

### ISSUE THREAD

**Issue by xX7** [braintree/braintree-android-drop-in#134]
# General information

* SDK/Library version: DropIn 4.2.0
* Environment: Sandbox & Production
* Android Version and Device: Google Pixel 2 XL / Android 9 - Official Rom

### Issue description

Referencing #122
PR: #126 

@scannillo @billwerges @quinnjn 

As I happened to encounter the same problem as stated in the issue above, I went on looking through the drop-in source code, to find that the `DropInActivity` is missing the call to `super.onActivityResult(...)`, so the` BraintreeFragments onActivityResult` won't get called. 

How to reproduce that behavior:

1. Code a custom implementation of a simple purchase flow with PayPal and attach the `BraintreeFragment` to this activity. 

2. Override `onActivityResult` **and remove the super call.** 

3. `onPaymentMethodNonceCreated` won't be called anymore.
 
**Edit:**

Looks to me as the same "thing" you tried to fix in order to get the Google Payment flow to work. By adding the super call, that should be fixed as well. 

Also: https://stackoverflow.com/questions/6147884/onactivityresult-is-not-being-called-in-fragment

**Edit2:**

Digging deeper I found a proof, that my suggested change will fix PayPal and the Google Payment flow:

The temporary fix for the Google Payment flow was to listen for `requestCode == 79129` while the activity was started with` BraintreeRequestCodes.GOOGLE_PAYMENT = 13593`. Giving the fact, that the `BraintreeFragment` is the only Fragment attached to the activity the `fragmentIndex` should be **1**.

originalRequestCode = changedRequestCode - (indexOfFragment << 16)
13593 = 79129 - ( 1 << 16)
13593 = 79129 - 65536
13593 = 13593

This points out, that the `onActivityResult` call with` requestCode = 79129` isn't due to a bug in the Google Payment activity, but just the fact that it is altered so it reaches it's correct fragment with a call to `super.onActivityResult`

**Comment by crookedneighbor** [comment]
Would you like to open a pull request?

**Comment by scannillo** [comment]
This issue was fixed with this PR: https://github.com/braintree/braintree-android-drop-in/pull/135
