### ISSUE TITLE
Request: Hide vaulted payments setting?

### ISSUE THREAD

**Issue by rtchang** [braintree/braintree-android-drop-in#139]
### General information

* SDK/Library version: Any
* Environment: Both
* Android Version and Device: Any

### Issue description

Not sure if this should be supported within the Drop-In or not, but the scenario that I have is for only adding a payment method. I was wondering if there was any way to hide (without forking and making changes) the list of recent payment methods (vaulted with nonces)?

Additional information below:
The user flow that I have is that we have a list of payment methods already used for payments, and we have an "add payment" button, which we then open the drop-in. It seems silly that the list of vaulted payments shows up in this scenario as it is redundant to the information shown on the list-view before. The intent at this point is that to add and not review currently-existing payment methods.

Any advice will be duly appreciated. Thank you.

**Comment by scannillo** [comment]
Hello @rtchang. To confirm our understanding, can you describe how you are currently vaulting payment methods?

Currently, there is no way in drop-in to hide vaulted payment methods.

**Comment by rtchang** [comment]
Currently we use the drop-in in two ways. One is for checkout and one is to manage payment methods that the client has added. We are adding the card with the nonce, sending it to our server. That card will now show up in the "Recently Added" section of the drop-in.

Correct me if I am wrong, but when you add those cards to the list of "recently added", it adds it to the vault?

**Comment by scannillo** [comment]
> Currently we use the drop-in in two ways. One is for checkout and one is to manage payment methods that the client has added. We are adding the card with the nonce, sending it to our server. That card will now show up in the "Recently Added" section of the drop-in.

Ok, so it sounds like you are vaulting payment methods yourself by sending it to your server. Is there a specific reason you're doing this instead of just enabling `DropInRequest.vaultCard` to `true` [(link)](https://github.com/braintree/braintree-android-drop-in/blob/c73f04e61f13071a1f59a70109ca04eea4bd915a/Drop-In/src/main/java/com/braintreepayments/api/dropin/DropInRequest.java#L181-L193)? This will handle vaulting for you without you having to make the requests yourself. (I assume you're doing this because you want to handle your own UI of vaulted payments?).

> Correct me if I am wrong, but when you add those cards to the list of "recently added", it adds it to the vault?

You are correct!

**Comment by rtchang** [comment]
It looks like the vaultCard option is set to true by default (which we are not overriding).
So we are vaulting it in addition to vaulting it on our service.
The reason we want our service to handle it is to be multi-platform (if you switch devices, the payment methods should follow from an iphone to an android to a tablet) and to support subscriptions.

**Comment by scannillo** [comment]
I understand. If you vault using the appropriate customer information (customerID), their vaulted payment methods will be available across all device types. You shouldn't need to handle vaulting per device type, if the customerID is consistent across devices.

As I said before, there is currently is no way in drop-in to hide vaulted payment methods. So here are some suggestions. 1) Continue to collect payment information via drop-in and utilize the drop-in's UI for displaying saved payment methods. 2) If you need to handle the UI of saved payment methods on your own, considering integrating without drop-in and using solely our core [Braintree SDK](https://github.com/braintree/braintree_ios).
