### ISSUE TITLE
ETA - next release

### ISSUE THREAD

**Issue by bblackbelt** [braintree/braintree-android-drop-in#14]
Hi Guys, do you have already an ETA for the next release (the one that contains the fix for android pay)?

Thanks

**Comment by sdcoffey** [comment]
Hey @bblackbelt - we'll get this out this week, thanks for the reminder. I'll close this issue when it's released.

**Comment by bblackbelt** [comment]
Thanks @sdcoffey . We would like to release a new version of our app tomorrow (CET) with this fix. Is it a JitPack mirroring feasible?

please advise

**Comment by sdcoffey** [comment]
Just released! Should be available via maven soon.

Thanks again for lending a hand with this fix!
