### ISSUE TITLE
Error when Gradle Sync release 4.3.0 

### ISSUE THREAD

**Issue by justColbs** [braintree/braintree-android-drop-in#142]
### General information

I am trying to solve the issue fixed in [this PR](https://github.com/braintree/braintree-android-drop-in/pull/135) by upgrading the DropIn SDK to 4.3.0 from 4.2.0. 

When I update the version and sync, I get the following error: 

`ERROR: Failed to resolve: org.jfrog.cardinalcommerce.gradle:cardinalmobilesdk:2.1.4-1
`

The dependency line: 
 `implementation 'com.braintreepayments.api:drop-in:4.3.0'`

In [Releases](https://github.com/braintree/braintree-android-drop-in/releases), it shows 4.3.0 is the latest public release.

What am I doing wrong? Thanks!

* SDK/Library version: 4.3.0

**Comment by Epreuve** [comment]
@justColbs You'll need to add the Cardinal Maven repository to your `build.gradle` as shown [here in the docs](https://developers.braintreepayments.com/guides/3d-secure/migration/android/v3#update-your-sdk-version).  Drop-in specific documentation is coming, but this should resolve the error you're seeing.

**Comment by justColbs** [comment]
@Epreuve Thanks so much! That worked.
