### ISSUE TITLE
Remove AndroidPay from recents

### ISSUE THREAD

**Issue by bblackbelt** [braintree/braintree-android-drop-in#15]
Hi Guys, 
  I am trying to find a way to remove AndroidPay from the "recents" in the Drop In but it seems not to be possible with current implementation. Google asked us to hide them during the review.

Please advise
Best,

**Comment by sdcoffey** [comment]
@bblackbelt - sorry for the late response. The payment methods that show up in `recents` are vaulted payment methods. We don't vault Android Pay automatically client-side in Drop-in, like we do for credit cards and PayPal, meaning that you should only see Android Pay show up in `recents` if you're vaulting server-side. Can you confirm that this is or isn't happening on your end?

**Comment by hellmund** [comment]
@sdcoffey Yes, we see vaulted Android Pay payment methods server-side on Braintree. As we will have up to 2 Android Pay payment methods active at a time (one for single transactions, one to be used for an active subscription), we are still looking for a way to hide the "other" one in the "recents" or to remove AndroidPay from the "recents" in the Drop-in in general.

**Comment by sdcoffey** [comment]
@hellmund After talking with the team about this, we're actually just going to always filter vaulted Android Pay cards. @lkorth is going to work on this today. I'll re-close this issue when we release.

**Comment by bblackbelt** [comment]
@sdcoffey, thanks!

**Comment by lkorth** [comment]
@bblackbelt this has been fixed and will go out in the next release soon. Thanks for reporting the issue!

**Comment by bblackbelt** [comment]
Thanks @lkorth!
