### ISSUE TITLE
Use a double for amount for 3D Secure 2.0

### ISSUE THREAD

**Issue by dadino** [braintree/braintree-android-drop-in#152]
### General information

* SDK/Library version: 4.3.0
* Environment: Sandbox or Production
* Android Version and Device: 5+

### Issue description

We wasted 2 days trying to understand why the credit card flow was not working. When clicking "Add card" ("Aggiungi carta" in Italian), the button would transform to a progressbar and then go back to button, no message displayed. In our logs we had the Paypal-debug-id, that from my understanding is something to pass to the assistance, no other useful informations.

Turns out the problem was the amount field, used for 3D Secure 2.0. The library asks for a String, which is strange, since it only accept a double with a dot (.) separator. We're an Italian company and in our Locale the separator is a comma (,) so our initial implementation was not working. Nowhere it is specified that it needs to be a dot.

All this could be easily skipped by requiring a double instead of a String. Or at least have a meaningful error message.

This is our current implementation, for anyone who'll need it:

    DecimalFormatSymbols formatSymbols = DecimalFormatSymbols.getInstance();
    formatSymbols.setDecimalSeparator('.');
    final String amount = new DecimalFormat("#.00", formatSymbols).format(product().getPrice());

**Comment by scannillo** [comment]
Hello @dadino . Thanks for pointing this out! We will update the docstring on `ThreeDSecureRequest.amount` to be more clear.

Just to confirm, are you generating your client token or tokenization key using the proper `merchantID` configured with your appropriate country/ currency?

**Comment by dadino** [comment]
> Just to confirm, are you generating your client token or tokenization key using the proper `merchantID` configured with your appropriate country/ currency?

We just checked and our sandbox is configured with a US timezone and EUR currency. Was the error due to this? What will happen when I use the dot String in the live server that has the Italian timezone?

**Comment by scannillo** [comment]
Ok, glad we checked! Definitely make sure your sandbox is configured with the appropriate timezone and currency.

You should be fine to pass in your regular currency format.
