### ISSUE TITLE
How to change button color in bt_add_card_activity ? I'm using the lib via gradle

### ISSUE THREAD

**Issue by Moseqi** [braintree/braintree-android-drop-in#154]

**Comment by Epreuve** [comment]
@Moseqi You can technically change the color of the buttons by creating a `colors.xml` file in your `res/values` directory inside your project, and overriding the values for `bt_blue` to your preferred button color, and `bt_white` to your preferred text color for the buttons.

This will effect all buttons within the Braintree Drop-in however, as they all use the same base `AnimatedButton` for styles and functionality.
