### ISSUE TITLE
It's a question. How to get List paymentMethodNonces?. I use lib in gradle.

### ISSUE THREAD

**Issue by Donhv** [braintree/braintree-android-drop-in#156]
* SDK/Library version: com.braintreepayments.api:drop-in:3.+

How to get List paymentMethodNonces with drop-in sdk? use DropInResult.fetchDropInResult() only get last nonce. 
I mean get list recent to show pop-up : Would you like to save payment details for future transaction? when not select payment details in List. 

<img width="379" alt="Screen Shot 2019-09-11 at 10 28 12" src="https://user-images.githubusercontent.com/16864971/64666071-2e0c3d80-d47f-11e9-9119-da6a24abac0e.png">

Note: In drop-in ios i can get List by: 
`    BTAPIClient *apiClient = [[BTAPIClient alloc] initWithAuthorization:clientToken];
`
`[apiClient fetchPaymentMethodNonces:^(NSArray<BTPaymentMethodNonce *> * _Nullable paymentMethodNonces, NSError * _Nullable error) {
        NSLog(@"result = %@", paymentMethodNonces);
    }];`

**Comment by Epreuve** [comment]
Hey @Donhv I believe `PaymentMethod#getPaymentMethodNonces` is the equivalent of what you're looking for on Android.  You can take a look at the Javadocs for it [here](https://static.javadoc.io/com.braintreepayments.api/braintree/3.6.0/com/braintreepayments/api/PaymentMethod.html#getPaymentMethodNonces-com.braintreepayments.api.BraintreeFragment-).
