### ISSUE TITLE
Cannot go back to app after chrome/ web UI Samsung devices

### ISSUE THREAD

**Issue by ericn37** [braintree/braintree-android-drop-in#16]
Happened on:
- S4 running Android 5.0
- Note 2 Android 4.4.2
- S5 Android 6.0.1

Both close button on top left corner of the screen and physical back button leads to the previous page in the browser history e.g. cnn.com instead of go back to my app

This issue didn't happen a month ago.

I'm using latest Braintree  Drop-in 3.0.4.
I've tried downgrading the library to 3.0.3, 3.0.2, 3.0.1 and 3.0.0 but the issue remains the same.
![device-2017-01-06-125553](https://cloud.githubusercontent.com/assets/19919208/21708025/8f00f888-d40f-11e6-8fc8-100a440d0269.png)
![device-2017-01-06-125905](https://cloud.githubusercontent.com/assets/19919208/21708078/eecf4bc0-d40f-11e6-9ae5-a87d578206bf.png)

![device-2017-01-06-125509](https://cloud.githubusercontent.com/assets/19919208/21708027/8f225e60-d40f-11e6-9f6a-0165255980bd.png)

**Comment by sdcoffey** [comment]
Hey @ericn37,

what `resultCode` are you getting back from Drop-in? If you're getting back something other `RESULT_OK`, you can query the intent for `DropInActivity.EXTRA_ERROR` for detailed information about why the browser switch might have failed.

**Comment by sdcoffey** [comment]
This is actually an issue with vanilla Braintree. I'm going to close this issue. Recreated [here](https://github.com/braintree/braintree_android/issues/137).
