### ISSUE TITLE
cannot implement braintree to AndroidManifast

### ISSUE THREAD

**Issue by zionnoizy** [braintree/braintree-android-drop-in#162]
I want to implement braintree payment method inside my android app. As I first put implementation 'com.braintreepayments.api:drop-in:4.4.1', I get the errors below. 
### The first error message I get is:

> ERROR: In project 'app' a resolved Google Play services library dependency depends on another at an exact version (e.g. "[1.3.1
> ,2.3]", but isn't being resolved to that version. Behavior exhibited by the library will be unknown.
> 
> Dependency failing: com.nimbusds:nimbus-jose-jwt:7.0.1 -> net.minidev:json-smart@[1.3.1,2.3], but json-smart version was
>  2.3.
> 
> The following dependencies are project dependencies that are direct or have transitive dependencies that lead to the art
> ifact with the issue.
> -- Project 'app' depends onto com.braintreepayments.api:drop-in@{strictly 4.4.1}
> -- Project 'app' depends onto com.nimbusds:nimbus-jose-jwt@{strictly 7.0.1}
> -- Project 'app' depends onto net.minidev:json-smart@{strictly 2.3}
> -- Project 'app' depends onto com.braintreepayments.api:three-d-secure@{strictly 3.4.1}
> -- Project 'app' depends onto com.braintreepayments.api:drop-in@4.4.1
> 
> For extended debugging info execute Gradle from the command line with ./gradlew --info :app:assembleDebug to see the dep
> endency paths to the artifact. This error message came from the google-services Gradle plugin, report issues at https://
> github.com/google/play-services-plugins and disable by adding "googleServices { disableVersionCheck = false }" to your b
> uild.gradle file.

`

### Then, I disable Google Service as below:
`com.google.gms.googleservices.GoogleServicesPlugin.config.disableVersionCheck = true`

### After that, I realize I need to put [3D secure](https://developers.braintreepayments.com/guides/3d-secure/migration/android/v3#update-your-sdk-version) inside the Manifast. The is my androidManifast below:

```
apply plugin: 'com.android.application'
apply plugin: 'com.google.gms.google-services'

android {
    compileSdkVersion 28
    buildToolsVersion "29.0.2"
    defaultConfig {
        applicationId "com.example.hungrystomach"
        minSdkVersion 28
        targetSdkVersion 28
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        multiDexEnabled true
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    implementation 'com.google.android.material:material:1.0.0'
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.2.0'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'
    implementation 'com.google.firebase:firebase-analytics:17.2.0'
    implementation 'com.google.firebase:firebase-auth:19.1.0'
    implementation 'com.google.firebase:firebase-database:19.0.0'
    implementation 'com.google.gms:google-services:4.3.1'
    implementation 'com.google.firebase:firebase-storage:19.0.0'
    //implementation 'com.android.support:design:28.0.0'
    implementation 'androidx.appcompat:appcompat:1.1.0'
    implementation 'com.squareup.picasso:picasso:2.71828'
    implementation 'com.android.support:recyclerview-v7:28.0.0'
    implementation 'com.android.support:appcompat-v7:28.0.0'
    implementation 'androidx.gridlayout:gridlayout:1.0.0'
    implementation 'androidx.cardview:cardview:1.0.0'
    implementation 'com.github.bumptech.glide:glide:4.8.0'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.8.0'
    implementation 'com.firebaseui:firebase-ui-database:4.3.2'
    implementation 'com.google.firebase:firebase-analytics:17.2.0'
    implementation 'com.google.firebase:firebase-messaging:20.0.0'
    implementation "androidx.legacy:legacy-preference-v14:1.0.0"
    implementation "androidx.preference:preference:1.1.0"
    implementation "com.android.support:support-compat:28.0.0"
    implementation 'com.cepheuen.elegant-number-button:lib:1.0.2'
    implementation 'com.google.android.gms:play-services-wallet:18.0.0'
    implementation 'com.android.support:appcompat-v7:28.0.0'
    implementation 'com.google.firebase:firebase-database:11.8.0'
    implementation 'com.firebaseui:firebase-ui-database:3.1.3'
    implementation 'com.android.billingclient:billing:1.2'
    implementation 'androidx.appcompat:appcompat:1.1.0'
    implementation 'com.craftman.cardform:cardform:0.0.2'
    implementation 'com.braintreepayments.api:drop-in:4.4.1'
    implementation 'org.jfrog.cardinalcommerce.gradle:cardinalmobilesdk:2.1.4-1'

    components.all {
        allVariants {
            withDependencies { deps ->
                deps.each { dep ->
                    if (dep.group == 'net.minidev' && dep.name =='json-smart') {
                        dep.version {
                            prefer "2.3"
                        }
                        dep.because "resolving dependencies issue"
                    }
                }
            }
        }
    }


    //https://firebase.google.com/docs/android/setup#available-lcardinalcommerceibraries
}
com.google.gms.googleservices.GoogleServicesPlugin.config.disableVersionCheck = true


repositories {
    maven {
        url "https://cardinalcommerce.bintray.com/android"
        credentials {
            username 'braintree-team-sdk@cardinalcommerce'
            password '220cc9476025679c4e5c843666c27d97cfb0f951'
        }
    }
}`
```

### Okay, this time sync in app works... Finally. At the time I compile my Android program......

> `W/e.hungrystomac: Bad encoded_array value: Failure to verify dex file '/data/app/com.example.hungrystomach-pVr20RazyRI6G6ALmCImJA==/base.apk': Bad encoded_value method type size 7
> **E/LoadedApk: Unable to instantiate appComponentFactory
>     java.lang.ClassNotFoundException: Didn't find class "androidx.core.app.CoreComponentFactory" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.example.hungrystomach-**pVr20RazyRI6G6ALmCImJA==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.hungrystomach-pVr20RazyRI6G6ALmCImJA==/lib/arm64, /system/lib64]]
>         at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
>         at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
>         .......
>         at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5780)
>         at android.app.ActivityThread.access$1200(ActivityThread.java:206)
>         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1678)
>         at android.os.Handler.dispatchMessage(Handler.java:106)
>         at android.os.Looper.loop(Looper.java:193)
>         at android.app.ActivityThread.main(ActivityThread.java:6702)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:911)
>     	**Suppressed: java.io.IOException: Failed to open dex files from /data/app/com.example.hungrystomach-pVr20RazyRI6G6ALmCImJA==/base.apk because: Bad encoded_array value: Failure to verify dex file '/data/app/com.example.hungrystomach-pVr20RazyRI6G6ALmCImJA==/base.apk': Bad encoded_value method type size 7**
>                     ..........
>         		... 12 more
> D/AndroidRuntime: Shutting down VM
> E/AndroidRuntime: FATAL EXCEPTION: main
>     Process: com.example.hungrystomach, PID: 28238
>     java.lang.RuntimeException: Unable to get provider com.google.firebase.provider.FirebaseInitProvider: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.provider.FirebaseInitProvider" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.example.hungrystomach-pVr20RazyRI6G6ALmCImJA==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.hungrystomach-pVr20RazyRI6G6ALmCImJA==/lib/arm64, /system/lib64]]
>         at android.app.ActivityThread.installProvider(ActivityThread.java:6427)
>         at android.app.ActivityThread.installContentProviders(ActivityThread.java:5969)
>         at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5884)
>         at android.app.ActivityThread.access$1200(ActivityThread.java:206)
>         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1678)
>         at android.os.Handler.dispatchMessage(Handler.java:106)
>         at android.os.Looper.loop(Looper.java:193)
>         at android.app.ActivityThread.main(ActivityThread.java:6702)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:911)
>      **Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.provider.FirebaseInitProvider" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file** "/data/app/com.example.hungrystomach-pVr20RazyRI6G6ALmCImJA==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.hungrystomach-pVr20RazyRI6G6ALmCImJA==/lib/arm64, /system/lib64]]
>         at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
>         at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
>         at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
>         at android.app.AppComponentFactory.instantiateProvider(AppComponentFactory.java:121)
>         at android.app.ActivityThread.installProvider(ActivityThread.java:6411) 
>         ....
>         at android.app.ActivityThread.main(ActivityThread.java:6702) 
>         at java.lang.reflect.Method.invoke(Native Method) 
>         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:911) 
>     	**Suppressed: java.io.IOException: Failed to open dex files from /data/app/com.example.hungrystomach-pVr20RazyRI6G6ALmCImJA==/base.apk because: Bad encoded_array value: Failure to verify dex file '/data/app/com.example.hungrystomach-pVr20RazyRI6G6ALmCImJA==/base.apk': Bad encoded_value method type size 7**
>         at dalvik.system.DexFile.openDexFileNative(Native Method)
>         ....
>         at android.app.ContextImpl.createAppContext(ContextImpl.java:2346)
>         at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5780)
>         		... 8 more

`
I have no idea why I still get the error and what "Unable to instantiate appComponentFactory" and  "because: Bad encoded_array value: Failure to verify dex file '/data/app/com.example.hungrystomach-pVr20RazyRI6G6ALmCImJA==/base.apk': Bad encoded_value method type size 7" are. I have no luck to find solution so far.. Any help could appricate.

**Comment by zionnoizy** [comment]
I solve the issue. Add the following in AndroidManifast inside Android { }

```
compileOptions {
        targetCompatibility JavaVersion.VERSION_1_8
    }
```
Please add the more instruction on readme about the java version. thanks

**Comment by scannillo** [comment]
Hello @zionnoizy. I am glad you found the link to our docs to fix the dependency resolution issue for using the Google Play Services Gradle plugin in addition to Braintree Three D Secure.

However, it looks like the second, compile-time, log regarding `encoded_array value` that you included does not point to anything Braintree SDK specific.

I am glad you resolved it!
