### ISSUE TITLE
Want to automate Braintree payment methods in appium with node.js 

### ISSUE THREAD

**Issue by waqaszulfiqar** [braintree/braintree-android-drop-in#170]
### General information

* Environment:  Sandbox 
* Android Version and Device: Google Pixel 2 Android 9.0 

### Issue description

 I want to automate the Braintree but I can't able to find the XPath. So any suggestion how I implement that as everything is completed just left with that  

**These are the fields** 
Card Number 
Expiry Date
CVC
Post Code
Add Card

**Comment by scannillo** [comment]
Hi. Since your question is specific to using [Appium](https://github.com/appium/appium), I suggest you reach out to them.

If you find an issue with our SDK, you can let us know.

**Comment by sestevens** [comment]
Hi @waqaszulfiqar I'm not sure if I understand the specific issue you're running into, but it may help to take a look at the [layout files](https://github.com/braintree/braintree-android-drop-in/tree/master/Drop-In/src/main/res/layout) for Drop-in.

**Comment by sestevens** [comment]
If you're looking for card form fields in particular, those layout files live in the [android-card-form](https://github.com/braintree/android-card-form) repo. In particular, you might want to look at [bt_card_form_fields.xml](https://github.com/braintree/android-card-form/blob/master/CardForm/src/main/res/layout/bt_card_form_fields.xml).

**Comment by juliamaksimchik** [comment]
Hi @waqaszulfiqar !

On my project we encountered the same issue. Seems like there are a limitation with iframes in Appium. Here is related [issue](https://github.com/appium/appium/issues/9464). They suggest a workaround there, but it won't work in case with Braintree (as Braintree fields won't render not within iframe)

There are a few possible solutions (that we brainstormed): 

1. You can prefill booking data for your tests. Like it suggested [here](https://github.com/braintree/braintree-web/issues/421). We didn't go this way as it requires to change our code only for tests. 

2. Using [touchAction](https://webdriver.io/docs/api/browser/touchAction.html) click on the form. It requires you to implement a logic of guessing where (on X/Y asis) you inputs are located.  

Hope it helps!

**Comment by scannillo** [comment]
Hello. I am going to close this issue as it seems more a limitation of the Appium framework you are using. Also, not sure if you're using one of our Android SDKs or our Web SDKs.

If you find an issue with our SDK, feel free to open up another issue with specifics on how to replicate.
