### ISSUE TITLE
502 errors from maven

### ISSUE THREAD

**Issue by chadallen87** [braintree/braintree-android-drop-in#171]
### General information
Something seems to have gone bad in maven, gradle cant pull the resources for my version. was working an hour ago, haven't changed anything for gradle config.

* SDK/Library version: com.braintreepayments.api:drop-in:3.+
* Environment: sandbox
* Android Version and Device: wont compile in android studio, but was working an hour ago, haven't changed anything about my gradle configuration

### Issue description
Error when trying to build the app:

Could not determine the dependencies of task ':processNormalDebugResources'.
> Could not resolve all task dependencies for configuration ':normalDebugRuntimeClasspath'.
   > Could not resolve com.braintreepayments.api:drop-in:3.+.
     Required by:
         project :
      > Failed to list versions for com.braintreepayments.api:drop-in.
         > Unable to load Maven meta-data from https://oss.sonatype.org/content/repositories/snapshots/com/braintreepayments/api/drop-in/maven-metadata.xml.
            > Could not HEAD 'https://oss.sonatype.org/content/repositories/snapshots/com/braintreepayments/api/drop-in/maven-metadata.xml'. **Received status code 502 from server: Bad Gateway**

**Comment by chadallen87** [comment]
if i replace with specific 3.7.1 version it compiles properly, just weird it has worked for months the other way until within an hour ago

**Comment by scannillo** [comment]
Hi @chadallen87. Could you include some relevant snippets from your `build.gradle` including the repositories `url`s you reference?

**Comment by sestevens** [comment]
I'm assuming this was resolved since we haven't gotten a response. Closing the issue.
