### ISSUE TITLE
Demo App Always Says "Postal code is invalid"

### ISSUE THREAD

**Issue by srkreddykrify** [braintree/braintree-android-drop-in#173]
Hi Team Currently am working on braintree Android sdk integration in Android project. I am facing an issue ie while try do adding an card using drop in ui version 4.5.1 am getting error code ie postal code invalid .
Environment: Sandbox

**Comment by scannillo** [comment]
If you need help troubleshooting your integration, reach out to Braintree Support at https://help.braintreepayments.com.

Only open an issue here if you think you've found an issue with our SDK.  If so, please fill out our issue template so we can replicate your issue.
