### ISSUE TITLE
Request new translation for bt_add_card in French

### ISSUE THREAD

**Issue by calvarez-ov** [braintree/braintree-android-drop-in#175]
### General information

* SDK/Library version: 4.5.0
* Environment: Sandbox and Production
* Android Version and Device: All

### Issue description

The French translation for `bt_add_card` is the same as [`bt_save_card_checkbox_name`](https://github.com/braintree/android-card-form/blob/4.2.0/CardForm/src/main/res/values-fr/strings.xml#L30): "Enregistrer une carte", which means "Save a card". This confuses French users who see a checkbox to save the card, and also a button to save the card. If they leave the checkbox unchecked, they still have to click on a button to "save" the card, so they end up unsure if the card was actually "saved" or not.

New translation suggestion for `bt_add_card`: "Ajouter carte"

Note, this translation is consistent with the other translations of `bt_add_card` which are all translations of "Add card". However, we find that a more understandable button label could be "Choisir cette carte" (Choose this card). However, we do not have the expertise to provide the equivalent translation in the other languages, for "Choose this card".

**Comment by sshropshire** [comment]
Hey @calvarez-ov! I've forwarded this to our localization team we should get a response in the next couple of days.

**Comment by sshropshire** [comment]
Hello @calvarez-ov, looking to resolve this issue soon.

Would you happen to have screenshots for this issue? We're working closely with our i18n team and close to providing a fix.

**Comment by calvarez-ov** [comment]
I happen to have this screenshot on hand, in English:

![1C800BA2-D7A2-487A-88A0-8DA062019BB2](https://user-images.githubusercontent.com/9365138/79013862-ef03af00-7b69-11ea-9d54-47356eb1634c.jpeg)

**Comment by sshropshire** [comment]
Hey @calvarez-ov would you happen to have a screenshot of the translation error in French?

**Comment by calvarez-ov** [comment]
Here you go:

![Screenshot_1586850495](https://user-images.githubusercontent.com/9365138/79199326-2194fc80-7e35-11ea-8176-5faea1685715.png)

**Comment by sshropshire** [comment]
Fixed in v4.6.0.
