### ISSUE TITLE
Braintree BrowserSwitchActivity doesn't call Activity Result

### ISSUE THREAD

**Issue by CosminMihuMDC** [braintree/braintree-android-drop-in#176]
### General information

* SDK/Library version: `implementation 'com.braintreepayments.api:drop-in:4.5.0'`
* Environment: Production

### Issue description

- Add item to checkout
- Go to checkout page and start to checkout
- Add new card (drop in bottom dialog is displayed -> select new card)
- 3d secure Web view will be displayed
- Fill with card data
- This page is displayed instead of returning to the app.
<img width="423" alt="Screenshot 2020-04-14 at 11 32 10" src="https://user-images.githubusercontent.com/2111663/79203522-d6ceb100-7e43-11ea-88e6-0c5e6121b31e.png">
- Click on RETURN TO APP.

**Actual Result:**
Will just show a blank activity and go back to browser
Video Dropbox  -> https://www.dropbox.com/s/7y008kwcoko1qgv/Video%2024-10-2018%2C%203%2057%2009%20PM.mov?dl=0

**Expected Result:**
Should return to Activity and call onActivityResult.

This issue is similar with https://github.com/braintree/braintree_android/issues/236 .

We have the same issue, but only on some phones is alsways reproducible: e.g Nokia 3 TA-1020.
On Pixel devices (2 and 4XL) the same code is working.

Do I miss something in implementation or it's really an issue?
Code related to braintree:

<img width="461" alt="Screenshot 2020-04-14 at 10 08 23" src="https://user-images.githubusercontent.com/2111663/79202866-e4d00200-7e42-11ea-91cb-87e26c689316.png">
<img width="743" alt="Screenshot 2020-04-14 at 11 17 53" src="https://user-images.githubusercontent.com/2111663/79202874-e7caf280-7e42-11ea-8974-63b672eb6abb.png">
<img width="717" alt="Screenshot 2020-04-14 at 11 16 59" src="https://user-images.githubusercontent.com/2111663/79202876-e7caf280-7e42-11ea-9010-2eaa6a81c883.png">
<img width="608" alt="Screenshot 2020-04-14 at 10 08 44" src="https://user-images.githubusercontent.com/2111663/79202870-e6012f00-7e42-11ea-8997-f2c93a85332f.png">
<img width="836" alt="Screenshot 2020-04-14 at 10 49 54" src="https://user-images.githubusercontent.com/2111663/79202872-e699c580-7e42-11ea-84d2-36da53abcc77.png">
<img width="631" alt="Screenshot 2020-04-14 at 10 51 50" src="https://user-images.githubusercontent.com/2111663/79202873-e7325c00-7e42-11ea-8e40-7cbf26c7afe3.png">

**Comment by scannillo** [comment]
Hey @CosminMihuMDC. Thanks for reaching out and providing details. So far, I'm unable to replicate what you're seeing on my Pixel 2 simulator. Is this an issue you can only replicate on real devices?

Also - can you check the **important** section of this[ browser switch setup guide](https://developers.braintreepayments.com/guides/client-sdk/setup/android/v2#browser-switch-setup)? And confirm that your scheme abides by the guidelines of no lowercase or underscores?

**Comment by CosminMihuMDC** [comment]
Thank you so much for quick reply. 

Actually, I didn't try with the simulator. I used real devices: Pixel 2, Pixel 4XL, Nokia 3.
On Pixels it's working, but on Nokia 3 not (as you can see above we are kind of stuck in the Webview - the blue button do not redirect in my app, instead it recreate the same webvew activity).

As you could see, I already add "Browser switch setup" in AndroidManifest and also my applicationId has no '_' character.

I would mention that I'm using https://developers.braintreepayments.com/guides/client-sdk/setup/android/v3, not Android V2 SDK. Should I used v2 instead?

I will try to get some logs and put them here, unfortunately right now I don't have that Nokia device with me, because of "work from home", but I will be back asap I have a phone with I can reproduce the issue.
It's a little strange that the same code on some devices is working, on other devices no.

**Comment by sshropshire** [comment]
Hi @CosminMihuMDC following up here. Are you still experiencing this issue?

**Comment by CosminMihuMDC** [comment]
Yes. But for now, we pause our development. 
I will close the issue.
Thanks.
