### ISSUE TITLE
No Error Displayed for Invalid Card on simplified AddCardActivity

### ISSUE THREAD

**Issue by rumburake** [braintree/braintree-android-drop-in#177]
### General information

* SDK/Library version: all, tried on`4.1.1` and `4.5.0`
* Environment: Production
* Android Version and Device: all, tried on Emulator as Pixel XL API 26, Android 8.0

### Issue description

When adding invalid card, there is no error indication, as shown in the picture:

<img width="365" alt="Braintree AddCardActivity" src="https://user-images.githubusercontent.com/5346099/79227916-8dd52780-7e58-11ea-9936-3d58cbf232ba.png">

We are using the Drop-In, and to add a card click Other -> Credit or Debit Card. This opens `AddCardActivity`. We are using a configuration where we register payment methods by adding only the long card number and expiry date. It works fine where the data is correct.

When we use an invalid card for testing, clicking the `ADD CARD` button loads a bit and then does not show any failure message which is confusing for the user. So the user keeps clicking on the button with no result.

We would expect some error message like for example in iOS:

![Braintree iOS](https://user-images.githubusercontent.com/5346099/79228879-143e3900-7e5a-11ea-8d38-b5920241cff6.jpeg)

Debugging Braintree we find the errors are:
 - container: BrainTree error for creditCard: null - which contains:
    1) BrainTree error for cvv: CVV verification failed
    2) BrainTree error for billingAddress: null

<img width="2193" alt="Braintree debug error" src="https://user-images.githubusercontent.com/5346099/79232443-66ce2400-7e5f-11ea-9b7d-838a7c72e182.png">

The error renderer can show errors in the `CardForm`:
 - expirationError, cvvError, postalCodeError, countryCodeError, mobileNumberError

...but none of them are displayed in this type of view which contains none of the associated fields:

<img width="1010" alt="Braintree Error Display Code" src="https://user-images.githubusercontent.com/5346099/79232291-3dad9380-7e5f-11ea-982d-a2d1aaa9e2f3.png">

So there is no error indication at all.

**Comment by sshropshire** [comment]
Hi @rumburake, thanks for using the Braintree SDK for Android.

Can you provide more information about how your DropInRequest is configured?

**Comment by rumburake** [comment]
Hi @sshropshire, thanks for looking into this I cannot post the configuration due to sensitive data. All we do is:

                val dropInRequest = DropInRequest().clientToken(data)
                dropInRequest.disablePayPal()
                startActivityForResult(dropInRequest.getIntent(context), REQUEST_CODE)

But this is irrelevant. The Add Card screen is configured to show only:
 - long card number
 - expiry date
As you see from the code and debug data, an invalid with a correct format has nowhere to print the error.

**Comment by rumburake** [comment]
I have sketched a fix above: 3bcbb13. Basically if there were some errors but none of them made it to the screen, display a generic error in an alert Dialog like in iOS.

The strings are hardcoded, but localisation data can be copied from the iOS implementation: https://github.com/braintree/braintree-ios-drop-in/pull/85

Sorry I had to fork to push as there was no permission to create branch.

**Comment by sarahkoop** [comment]
Hi @rumburake - we've made some updates to error handling in version `6.0.0-beta2`, can you confirm if you are still experiencing this issue with that version?

**Comment by rumburake** [comment]
@sarahkoop I regret I won't be able to help much here, I don't remember well the issue as I didn't work with payments in a long time. Great to see some progress BTW!

**Comment by sarahkoop** [comment]
@rumburake thanks for the update - I'm going to go ahead and close this issue then, but feel free to re-open if someone on your team is still experiencing the issue after upgrading.

**Comment by WishalKalkani** [comment]
@sarahkoop  its not resolved yet
even i update library but its still same
can you please resolve this?
