### ISSUE TITLE
Authorization Fingerprint Is Invalid

### ISSUE THREAD

**Issue by meidikawardana** [braintree/braintree-android-drop-in#179]
### General information

* SDK/Library version: 3.7.0 
* Environment: Sandbox and Production 
* Android Version and Device: happen on Redmi 5A (OS Oreo), Pixel (OS info n/a)

### Issue description

I get this error when implement Braintree to my android app.

`Request for configuration has failed: Authorization fingerprint is invalid. Future requests will retry up to 3 times`

I want to implement "add credit card" feature for customers.

![braintree error](https://user-images.githubusercontent.com/2024380/80460265-cba87480-895d-11ea-8ff5-824ad2b9bf71.png)

other info I can share
* using kotlin 1.3.50
* compileSdk 28, minSdk 21, targetSdk 28

I already posted this to stackoverflow too: https://stackoverflow.com/questions/61474889/braintree-authorization-fingerprint-is-invalid

Please help me.. I will provide any company-shareable info you need. Thank you

**Comment by scannillo** [comment]
Hello - to help troubleshoot your specific integration reach out to Braintree Support at https://help.braintreepayments.com. They will best be able to help you here.

**Comment by mooglife** [comment]
Hi there,

I faced this issue today. I was able to resolve it by asking a fresh Client Token(ofc programmatically). Client tokens are valid for 24 hrs, I read it somewhere on BT help guides.

Try using client tokens, which are no older than 24 hrs.

hope it helps.
m

**Comment by meidikawardana** [comment]
> Hi there,
> 
> I faced this issue today. I was able to resolve it by asking a fresh Client Token(ofc programmatically). Client tokens are valid for 24 hrs, I read it somewhere on BT help guides.
> 
> Try using client tokens, which are no older than 24 hrs.
> 
> hope it helps.
> m

thank you! I will try your solution

**Comment by gordonchanhk** [comment]
So, @meidikawardana just wonder refreshing the client token help stop that warning?
