### ISSUE TITLE
Venmo payment method- Unable to refresh issue

### ISSUE THREAD

**Issue by harirao001** [braintree/braintree-android-drop-in#18]
Hey,

I've used drop-in ui and trying to use venmo as my payment method.
On selecting Venmo I'm getting the below error:

"Unable to refresh
Please check your internet connection.
Try again"
![device-2017-01-10-030840](https://cloud.githubusercontent.com/assets/9672228/21807537/34be5c8e-d70d-11e6-801f-d0e0f9cf049e.png)

My internet is working fine and working internet in all other app of my device.
Its also working if I select other payment option.

I'm attaching screenshot for more clear picture.

Please help me to resolve this issue.

**Comment by sdcoffey** [comment]
I'm going to close this issue since it's been reposted [here](https://github.com/braintree/braintree_android/issues/138)
