### ISSUE TITLE
Not getting full deviceData

### ISSUE THREAD

**Issue by AndresPrietoTucasi** [braintree/braintree-android-drop-in#186]
### General information

* SDK/Library version: https://mvnrepository.com/artifact/com.braintreepayments.api/drop-in/4.6.0
* Environment: Sandbox
* Android Version and Device: Pixel 3 XL Pie 9.0 emulator

I have setup my dropInRequest as follows:
`DropInRequest dropInRequest = new DropInRequest()
                .ClientToken(_clientToken)
                .CollectDeviceData(true)
                .RequestThreeDSecureVerification(true)
                .InvokeThreeDSecureRequest(threeDSecureRequest)
                .MaskCardNumber(true)
                .MaskSecurityCode(true)
                .DisableVenmo()
                .DisablePayPal()
                .DisableGooglePayment()
                .VaultCard(true);`
I noticed when I capture the response the device data information is as follows:
{"correlation_id":"<content>"}
But when i collect the data through my website (with same emulator) with the JS API I get the following back
{"device_session_id":"<content>",
"fraud_merchant_id":"<content>",
"correlation_id":"<content>"}
Is this level of device data not available through this implementation? or have i missed a flag somewhere?
I did look at the documentation here:
https://developers.braintreepayments.com/guides/advanced-fraud-management-tools/device-data-collection/android/v3
But im not sure as to whether this is relevant as it references creating a BraintreeFragment, which it also states is required for the threeDSecure, but from the readme on here and my current setup that is not reuired for the 3d secure implementation, so i assume its not required here for the device data either?

**Comment by scannillo** [comment]
Hello @AndresPrietoTucasi. Can you tell us which SDK version you are using?

Also - can you provide a code snippet for how/where you're currently capturing `{"correlation_id":""}`?

**Comment by AndresPrietoTucasi** [comment]
Hi @scannillo my project is written in Xamarin so do be aware that it will be C# code, above i showed where I request it, but with rergards to where i catch it I have the following in my MainActivity.cs
`protected override void OnActivityResult(int requestCode, Result resultCode, Intent data)
        {
            base.OnActivityResult(requestCode, resultCode, data);
            AndroidPayService.OnActivityResult(requestCode, resultCode, data);
        }`
And then i pull the information out from data as follows:
DropInResult result = data.GetParcelableExtra(DropInResult.ExtraDropInResult).JavaCast<DropInResult>();
DeviceData = result.DeviceData

As for my Android SDK I have the following in my AndroidManifest.xml:
```
<manifest xmlns:android="http://schemas.android.com/apk/res/android" android:versionName="1.7.0" package="com.tucasi.scopay" android:installLocation="auto" android:versionCode="27" xmlns:tools="http://schemas.android.com/tools">
	<uses-sdk android:minSdkVersion="21" android:targetSdkVersion="28" />
```

**Comment by scannillo** [comment]
When you collect the device data through your web integration, are you also using drop-in on the web as well? 

In terms of how to use `deviceData` for use with 3DS transactions, I encourage you to continue reading our developer docs or reach out to Braintree Support at https://help.braintreepayments.com/ for help troubleshooting your specific integration.

**Comment by AndresPrietoTucasi** [comment]
Oh i see, in my web integration i am indeed also using the drop in UI which is version 1.22.1
For now i will contact the braintree support as you suggest
