### ISSUE TITLE
Payment with 3DS v2

### ISSUE THREAD

**Issue by simon-twonary** [braintree/braintree-android-drop-in#187]
### General information

* SDK/Library version: 4.6.0
* Environment: Production
* Android Version and Device: Tested Samsung, Xiaomi, and BLU. with Chrome installed and up to update.

### Issue description

The issue seems to be related to this incident. https://status.braintreepayments.com/incidents/zdcr8w4sv85g

Trying to verify with 3DS v2 and got this error.

![Screenshot_20200729-110042](https://user-images.githubusercontent.com/59780143/88934733-fbae2f00-d24e-11ea-98d6-19bcdd6d82bd.png)

the certificate seems to be valid

![WhatsApp Image 2020-07-29 at 16 24 53](https://user-images.githubusercontent.com/59780143/88934887-25675600-d24f-11ea-88c9-33a924389f75.jpeg)

**Comment by hollabaq86** [comment]
@simon-twonary can you confirm the timezone for these two screenshots?

**Comment by simon-twonary** [comment]
GTM-4

**Comment by simon-twonary** [comment]
GMT-4 for the second screenshot.

**Comment by simon-twonary** [comment]
seem fixed now. just tested a few transactions successfully.
