### ISSUE TITLE
I am not able to get Payer's Id anywhere. Can anyone please guide.

### ISSUE THREAD

**Issue by Shani618** [braintree/braintree-android-drop-in#192]
### General information

* SDK/Library version: 
* Environment: 
* Android Version and Device:

**Comment by sshropshire** [comment]
Hi @Shani618 thanks for using the Braintree SDK for Android. I would first consult our docs site on [PayPal Checkout](https://developers.braintreepayments.com/guides/paypal/overview/android/v3), and then reach out to our Support team if you need additional help troubleshooting your specific integration.

> Only open an issue here if you think you've found an issue with our SDK. If you need help troubleshooting your integration, reach out to Braintree Support at https://help.braintreepayments.com.
