### ISSUE TITLE
unsafe implementation of HostnameVerifier

### ISSUE THREAD

**Issue by mattaojie** [braintree/braintree-android-drop-in#194]
### General information

* SDK/Library version: 
* Environment: 
* Android Version and Device: 

### Issue description

**Security alert**

Your app is using an unsafe implementation of HostnameVerifier. Please see this Google Help Center article for details, including the deadline for fixing the vulnerability.

Vulnerable classes:

    lib.android.paypal.com.magnessdk.network.e$a
    lib.android.paypal.com.magnessdk.network.f$a

`api 'com.braintreepayments.api:drop-in:4.2.0'`

**Comment by DevToDipesh** [comment]
Hi @mattaojie We also got the same . Hope this will be resolved by Braintree Team soon.

**Comment by omkumar87** [comment]
are you guys using the latest versions after 4.5.0?

**Comment by sshropshire** [comment]
Hi @mattaojie I would suggest updating to the latest `v4.6.0` version of the Drop-In library.

**Comment by keval1040** [comment]
If upload version 4.6.0 and publish your app get below error any idea for this

Your app contains unsafe cryptographic encryption patterns. Please see this Google Help Center article for details.

Vulnerable classes:

com.cardinalcommerce.shared.cs.utils.a.a

**Comment by sshropshire** [comment]
Upgrading to version 4.6.0 appears to resolve the issue. For issues not related to unsafe implementation of `HostnameVerifier`, please open a separate issue so we can track its status properly.
