### ISSUE TITLE
UnionPay Declined

### ISSUE THREAD

**Issue by mattaojie** [braintree/braintree-android-drop-in#195]
### General information

* SDK/Library version:  drop-in 4.2.0 and 4.6.0
* Environment:  Production
* Android Version and Device: 

### Issue description

When I use UnionPay to pay, I got a "Declined" error, but there is no problem with visa or MasterCard.

**Comment by hollabaq86** [comment]
👋 please [contact Support](https://help.braintreepayments.com/) with your merchant ID and the authorization you're using to setup your client, they will be able to assist in troubleshooting your issue.
