### ISSUE TITLE
Braintree Google Play Store Notice

### ISSUE THREAD

**Issue by keval1040** [braintree/braintree-android-drop-in#197]
### General information

* SDK/Library version: 4.6.0
* Environment: Production
* Android Version and Device: Not Device Specific

### Issue description

I publish my App in production but get below noticed for play store please resolve ASAP because client is wait for application live

Your app contains unsafe cryptographic encryption patterns. Please see this Google Help Center article for details.

https://support.google.com/faqs/answer/9450925

Vulnerable classes:

com.cardinalcommerce.shared.cs.utils.a.a

**Comment by sshropshire** [comment]
Hi @keval1040 thanks for using the Braintree SDK for Android. Can you provide a link to the help center article mentioned above?

**Comment by keval1040** [comment]
Below is help center artical link

https://support.google.com/faqs/answer/9450925

**Comment by sshropshire** [comment]
@keval1040 understood this is an issue with the core SDK. We have an open issue and are working on a resolution. Please follow along [here](https://github.com/braintree/braintree_android/issues/305) for more updates.

**Comment by sshropshire** [comment]
Cardinal provided an update. This should now be fixed in version `3.14.2`.
