### ISSUE TITLE
Why is deviceData not collected if storeInVaultOnSuccess is set to true?

### ISSUE THREAD

**Issue by bikranttripathi** [braintree/braintree-android-drop-in#199]
I know this is not a conventional place to ask such a question but we have had Braintree integrated for years and are finally planning to add it for Android but realized that with the existing settings it's not possible to collect deviceData. Can you please help us figure this out? :) Thank you in advance

### General information

* SDK/Library version: 5.0.0
* Environment: Sandbox
* Android Version and Device: OnePlus 7 Pro with Android 10

### Issue description
- Device Data captured Flag is `false` on Braintree transaction page even though we are passing it from the Client -> Our backend -> Braintree
- What's the benefit of having `storeInVaultOnSuccess` set to true

### Additional Information
- We are using test cards from Braintree [testing page](https://developers.braintreepayments.com/reference/general/testing/php#valid-card-numbers) to make these purchases
- Kount is enabled
- `Advanced Fraud Tools Information` Section on the console for the transaction says that Device data wasn't captured

### Client side Integration:
```
fun fetchPaymentMethod() {
    val dropInRequest = DropInRequest().clientToken(token).collectDeviceData(true)
    activity.startActivityForResult(api.getIntent(activity), REQUEST_CODE)
}

override fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent?) {
   if (requestCode != REQUEST_CODE) return

   if (resultCode == Activity.RESULT_OK) {
       val result = data.getParcelableExtra<DropInResult>(DropInResult.EXTRA_DROP_IN_RESULT)
       val deviceData = result.deviceData  // value {"correlation_id":"XXX"}
       val paymentMethodNonce = result.paymentMethodNonce

       purchase(deviceData, paymentMethodNonce.nonce)
  }
}

fun purchase(deviceData: String, paymentMethodNonce: String) {
   // Send a request to Backend
}
```

### Backend Integration:
```
$result = Braintree_Transaction::sale(array(
                        'amount' => $amount,
                        'paymentMethodNonce' => $signature,
                        'options' => array(
                            'storeInVaultOnSuccess' => true,
                            'submitForSettlement' => false
                        ),
                        'deviceData' => $_POST['device_data'],
                        'customFields' => $userExtraData
                    ));
```

**Comment by crookedneighbor** [comment]
Reach out to our support team. They can help you troubleshoot your integration to make sure you're set up correctly: https://help.braintreepayments.com/
