### ISSUE TITLE
CustomerId() documentation

### ISSUE THREAD

**Issue by ahaverty** [braintree/braintree-android-drop-in#2]
The repo's readme and the braintree documentation suggest that I can pass in the customer's braintree id to show existing cards.
I can't find any technical documentation on how to do so, does this feature still exist?

https://developers.braintreepayments.com/guides/drop-in/android/v2#customer-id
> Customer ID
> If you pass a customerId() when generating the client token, the Drop-in will display that customer's saved payment methods and automatically add any newly-entered credit card payment methods to their Vault record.

And

**See image far right ->**
![](https://github.com/braintree/braintree-android-drop-in/raw/master/screenshot.png)

**Comment by ahaverty** [comment]
Just to answer my own issue, it looks like the customerId is passed in when requesting the client token **(NOT during creation of the dropin-ui)**. I was in the mindset of building the dropin-ui, hence my confusion.
Can I suggest both docs be updated with a **full** example, including passing in the customerId() during client token generation?


_I'd like to also suggest that all the features of the dropin-ui with the customerId be outlined somewhere. For example, can a user disassociate a payment method from their account via that 'Choose Payment Method' list? Can the default card be altered from that menu? etc._

**Comment by lkorth** [comment]
Correct, the `customer_id` is specified when generating a client token. If you click the `customer_id` link in the docs link you posted, it will take you to a page about generating client tokens.

We are in the process of updating the documentation for the new version of Drop-in so we'll make sure to include some additional information about vaulted payment methods. Currently passing a customer id only allows the user to select from their previously vaulted payment methods or vault a new one.

**Comment by ahaverty** [comment]
Great!, thanks Ikorth
