### ISSUE TITLE
Cannot access adding payment methods with external keyboard

### ISSUE THREAD

**Issue by huiningd** [braintree/braintree-android-drop-in#201]
### General information

* SDK/Library version: 5.0.0
* Environment: Production 
* Android Version and Device: Pixel 4 with Android Version : 10,  Pixel 3a XL with Android Version 11.

### Issue description

We are using Braintree drop-in UI for an app with accessibility requirements. For example we need to support external keyboard navigation, where user can use the Tab key on external keyboard to navigate through the UI. 
We noticed that with external keyboard navigation, clicking the Payment Method buttons (see below image) doesn't work. I tested with your drop-in UI Demo app and it has the same problem.
Keyboard I used is: Microsoft universal foldable keyboard, and connected to the phone with bluetooth.

To reproduce:
1. Install Android Braintree drop-in UI Demo app.
2. Connect the phone with an external keyboard.
3. Navigate to the screen below. Use Tab to move focus to one of the buttons under "Select Payment Method".
4. Click the button by pressing Enter. 
Expected: Button is clicked, the screen for adding payment method opens.
Actual: Nothing happens.

Note: when the drop-in UI opens (I tried adding credit card), I can enter card number from external keyboard. However if the on screen month/year selector opens, I couldn't move the focus from the month/year selector to the "ADD CARD" button.
<br>

![braintree-buttons](https://user-images.githubusercontent.com/13892182/96847542-fc282180-145b-11eb-8acf-868c7382d200.png)

**Comment by sarahkoop** [comment]
Hi @huiningd, thanks for using the Braintree SDK. We are currently in the process of making updates to improve accessibility in the Drop-In UI. I was able to reproduce this issue, and we will post updates here when changes are released.

**Comment by huiningd** [comment]
@sarahkoop Thank you so much! This is great news for us. :)

**Comment by sarahkoop** [comment]
@huiningd - Providing an update on this: we still have some accessibility and external keyboard navigation improvements to make, but all fields should be accessible by tab navigation in drop-in `v6.0.0-beta2`

**Comment by sarahkoop** [comment]
Version `6.0.0` of the Drop-in SDK has been released.
