### ISSUE TITLE
Insecure hostname verifier

### ISSUE THREAD

**Issue by achalkias** [braintree/braintree-android-drop-in#203]
I did the pre launch report and google find the following security and trust issue

**Your app is using an unsafe implementation of hostname verifier. Please see this Google Help Centre article for details, including the deadline for fixing the vulnerability.

Llib/android/paypal/com/magnessdk/network/d$1;
Llib/android/paypal/com/magnessdk/network/e$1;
sv:deadline:12/14/2020**

I have a deadline to secure my app until 12/14/2020
I use version 3.7.1 and i cannot update it because i have to also upgrade the whole project to android x 
Is there any workaround for this?

Thanks in advance

**Comment by sshropshire** [comment]
Hi @achalkias thanks for using the Braintree SDK for Android. Unfortunately, you will have to upgrade since this was fixed in a later version. While I recommend updating to the latest version whenever possible, in the short-term I believe `3.7.2` has the change you need.

Also if moving to `androidx` is an issue, consider using [Jetifier](https://developer.android.com/jetpack/androidx/migrate) to help ease the migration process.

**Comment by achalkias** [comment]
Greetings i found a workaround for this. 
You can make the implementation like this
`    
implementation 'com.braintreepayments.api:drop-in:3.+', {
        exclude group: 'com.android.support', module: 'appcompat-v7'
        exclude group: 'com.com.paypal.android.sdk', module:'data-collector'
}
`

` 
implementation 'com.paypal.android.sdk:data-collector:3.14.2'
`

Alson need to set 
`minSdkVersion 21`

This way google will accept your app and you wont get a security issue without updating braintree and have to migrate your project to androidx.

Happy Coding!

**Comment by DreadBoy** [comment]
I'm using version 4.1.1 and this doesn't seem to be fixed, I'm still getting same warning on Google Play.

**Comment by sshropshire** [comment]
@DreadBoy apologies, `4.5.0` of the drop-in library should be the correct version to eliminate this error. We resolved this issue in v3.7.2 of the core [Braintree SDK](https://github.com/braintree/braintree_android). I've made the correction above as well.
