### ISSUE TITLE
Unsafe implementation of the HostnameVerifier interface - vulnerability

### ISSUE THREAD

**Issue by marcin-owoc** [braintree/braintree-android-drop-in#208]
### General information

* SDK/Library version: 5.0.1
* Environment:Production
* Android Version and Device: Any device

### Issue description

I tried to publish app in Google Play, but my app has been rejected due to unsafe implementation of the HostnameVerifier interface.
I believe this is because Google Play changed policy and are not allowing anymore such a vulnerability.

I ran scanner to find potential sources in our app and report clearly say that Braintree SDK ( its dependencies) ignore SSL errors:

> WebHybridClient.java in PayPal 5.3 and earlier for Android ignores SSL errors, which allows man-in-the-middle attackers to spoof servers and obtain sensitive information.

Please fix your issue asap, since is blocking Google Play publishes.

**Comment by sshropshire** [comment]
HI @marcin-owoc thanks for using the Braintree SDK for Android. This should be resolved in Drop-In `5.0.1`. Can you share your Gradle dependencies block to help us investigate?

**Comment by marcin-owoc** [comment]
Hi @sshropshire I have only declared :

> implementation 'com.braintreepayments.api:drop-in:5.0.1'

in build.gradle.

**Comment by sshropshire** [comment]
Thanks @marcin-owoc. We created a test app with our drop-in library and uploaded it to the Google Play store. Unfortunately we were unable to reproduce the issue. Could there be another Gradle dependency in your app causing the error?

**Comment by marcin-owoc** [comment]
Do you mean app has not been rejected, because of HostnameVerifier vulnerability ?

It is really weird since when you run scanner for dependency check (org.owasp.dependencycheck):
it clearly says, that in current version of drop in 5.0.1, there still exist such a vulnerability ( for my app is only one SSL vulnerability ).

I have no more Gradle dependency from Braintree like only:
> implementation 'com.braintreepayments.api:drop-in:5.0.1'

Still waiting for Google support team to get more details, what is causing HostnameVerifier issue. Once will get it, I will come with answer.

**Comment by sshropshire** [comment]
We're using the Google Play Store Console and uploading an apk for test, which triggers a security scan. We've seen a similar issue with one of our dependencies that has been resolved since version `4.5.0`. Our recent upload did not contain the vulnerability as expected.

If there is more information available from the Google support team please let us know and we can help diagnose.

**Comment by marcin-owoc** [comment]
Got official info from Google support team, the issue is not resolved at all:

You can read through the Device and Network Abuse policy page for more details and examples of common violations.

For example, your app currently contains the following issue:

**Hostname Verifier**

For example, your app is currently using the following vulnerable implementation of HostnameVerifier:

**- Llib/android/paypal/com/magnessdk/network/d$1;
- Llib/android/paypal/com/magnessdk/network/e$1;**

To properly handle hostname verification, you'll need to change the verify method in your custom HostnameVerifier interface to return false whenever the hostname of the server does not meet your expectations. You may refer to the Alerts page of your Play Console and this Help Center for additional guidance.

Please make appropriate changes to your app, and be sure to address the issues identified above. In addition to your Production release, if you have other release types that you use for testing and/or quality assurance checks (e.g. Internal test, Closed, Open), please make sure to update those tracks as well.

Kindly note that all active versions of your app must be compliant with our policies including all release types. If there is any violating version code(s) present within the app, it will still be subject to future enforcements.

com.braintreepayments.api:drop-in:5.0.1 still contains com.braintreepayments.api:braintree:3.14.2, which has that vulnerability.

This is very urgent, since we are blocked for over 2 weeks with publish.

**Comment by dcheckoway** [comment]
@sshropshire here's the scoop.  We decompiled your code and (we believe) we found the smoking gun.

There are 2 different classes in the `lib.android.paypal.com.magnessdk.network` that are doing this in their `execute(byte[])` method:

```java
httpsurlconnection.setHostnameVerifier(lib.android.paypal.com.magnessdk.network.e.a());
```

And then when you look at what that `e.a()` method (name obviously obfuscated) is doing:

```java
    public static HostnameVerifier a()
    {
        return HttpsURLConnection.getDefaultHostnameVerifier();
    }
```

...it's simply passing through what's already set as the default.  This effectively accomplishes nothing.  The `httpsurlconnection.setHostnameVerifier()` call could theoretically be commented out with no impact.

Yet, Google "smarts" seem to think this is an insecure implementation.  Despite it just passing through the default.

Please remove this useless code ASAP.  I believe you can address this much more quickly than Google can update their "smarts" to detect this effectively circular reference.

THANK YOU!!!

**Comment by hollabaq86** [comment]
👋  @dcheckoway and @marcin-owoc Thanks for this info. We're checking in with our PayPal colleagues for feedback on this issue. Just to set expectations- with the holidays this week and next, our response time may be a little slower than usual.

**Comment by dcheckoway** [comment]
Happy new year!  Well, it would be happier if we could actually release our Android app!  😛  Any movement on this?

cross posting in https://github.com/braintree/braintree_android/issues/325, not sure which place will get more traction quicker

**Comment by kolja-ec** [comment]
Same issue here...

**Comment by sshropshire** [comment]
Hello all, we're aware that this is preventing app updates to the Google Play store. We're working with our colleagues at PayPal to get an updated version of the Magnes library for Android. Thank you for your patience.

**Comment by SolodilovEugene** [comment]
today removed the application from the market due to this error - (
![Снимок экрана 2021-01-06 в 11 44 28](https://user-images.githubusercontent.com/74347228/103754114-9851d580-5014-11eb-8203-5756e6bb1cf5.png)

**Comment by dcheckoway** [comment]
@hollabaq86 @sshropshire Weeks have gone by and this is starting to become unacceptable.  Significant revenue is at stake.  Our C-suite has us evaluating alternatives for payment processing.  I'm sure you're taking this seriously, but I urge to do whatever you can to accelerate the fix before this becomes the reason we go with a different partner.

**Comment by hollabaq86** [comment]
Hi everyone. Both us and our PayPal colleagues have given this issue the highest priority and are actively working on a resolution this sprint. We want to get this fixed asap, too! As soon as we receive an updated version of the Magnes SDK we can begin updating our SDK, running tests and prepping a release. We'll post updates in this issue when these events happen. Thank you for your patience and understanding.

**Comment by sshropshire** [comment]
The PayPal team has provided a fix and we've released a new `5.0.2` version of `braintree-android-drop-in` with the update.

**Comment by mayurchoudharyst2020** [comment]
@ssgelm 
I update my code with latest version but Google reject my app 
    implementation 'com.braintreepayments.api:drop-in:3.7.1'

**Comment by DuoBlood** [comment]
After I updated the library I got a reject again...

```
implementation "com.braintreepayments.api:braintree:3.15.0"
implementation "com.braintreepayments.api:data-collector:3.15.0"
implementation "com.braintreepayments.api:drop-in:5.0.2"
```

**Comment by kolja-ec** [comment]
Rejected and removed from app-store.

**Comment by sshropshire** [comment]
Thanks everyone we appreciate your feedback. We're aware that this issue is still being experienced by some after uploading to the Google Play Store. We're in the process of investigating further. In the meantime, if you've experienced success or failure when uploading to Google Play, please respond to this issue.

**Comment by sshropshire** [comment]
Hi @mayurchoudharyst2020 are you having the same issue with `braintree-android-drop-in` version `5.0.2` ?

**Comment by sshropshire** [comment]
Hi @DuoBlood and @kolja-ec can you drop a screenshot of what you're seeing in the Google Play console?

**Comment by alfaro28** [comment]
Hi, my app still got rejected after upgrading to 5.0.2

**Comment by sshropshire** [comment]
Hi @alfaro28 can you provide a screenshot of what you're seeing in the Google Play console?

**Comment by alfaro28** [comment]
It's in spanish but I hope it helps, https://ibb.co/GHytb83  also the email contains this bit of information:


Below is the list of issues and the corresponding APK versions that were detected in your recent submission. Please upgrade your app(s) as soon as possible and increment the version number of the upgraded APK.

Vulnerability | APK Version(s) | Past Due Date
-- | -- | --
HostnameVerifierYour app(s) are using an unsafe implementation of the HostnameVerifier interface. You can find more information about how resolve the issue in this Google Help Center article. | 32 | December 10, 2020

**Comment by marcin-owoc** [comment]
@sshropshire still the same with upgraded drop-in version:
_implementation 'com.braintreepayments.api:drop-in:5.0.2'_

<img width="1036" alt="Screenshot 2021-01-13 at 00 07 52" src="https://user-images.githubusercontent.com/1240364/104453965-7f619b00-55a5-11eb-8d42-8cc6c64b94af.png">

**Comment by alfaro28** [comment]
Just an update on my case, my app with version 5.0.2 was approved, I was doing a partial deploy 0.1% of users, and the previous attempt at doing a 100% version was using an old version of braintree so it was getting rejected, when I changed to 100% with the new version it got approved.

**Comment by DuoBlood** [comment]
Hey @sshropshire, sorry for the delay.

![Screenshot at Jan 14 02-09-41](https://user-images.githubusercontent.com/5984618/104527529-9d62e600-560d-11eb-8059-f41b20a7c6c9.png)

**Comment by marcin-owoc** [comment]
OK, we are finally live.
Make sure you make release 100% ( full rollout ) and you update all tracks, including open, closed and internal tracks.
Vulnerability cannot be included on any of them.

**Comment by DuoBlood** [comment]
Thanks @marcin-owoc  
We are finally live.
The rollout should be 100% if its less Play Store will reject the app with the same issue without any additional info.

**Comment by outlookamusements** [comment]
> OK, we are finally live.
> Make sure you make release 100% ( full rollout ) and you update all tracks, including open, closed and internal tracks.
> Vulnerability cannot be included on any of them.

Can you please help how to resolve this issue with 5.0.2.

where you are doing 100% ( full rollout )

**Comment by jawaharravi** [comment]
In addition to your Production release, if you have other release types that you use for testing and/or quality assurance checks (e.g. Internal test, Closed, Open), please make sure to update those tracks as well.

This rejection doesn't impact the standing of your Google Play Developer Account, but repeated violations can result in the suspension of this app or your Google Play Developer account.

Before resubmitting your app for further review, please make sure to DEACTIVATE the non-compliant APK (APK Version Code:***) and increment the version number of the APK. Kindly note that all active APK versions need to be compliant.

(Add the compliant app bundle with the non complaint app bundle). Submit your updated APK. This will make sure that there are no tracks running with non-compliant version.
