### ISSUE TITLE
No way for user to choose Android Pay methods after first donation

### ISSUE THREAD

**Issue by mrsasha** [braintree/braintree-android-drop-in#21]
Hi,

one of the requirements from Google Android Pay team is for user to be able to change the Android Pay payment methods for subsequent payments, should he want to. Here's how our payment screen looks like:

![payment-second_payment-picker](https://cloud.githubusercontent.com/assets/1850452/22595686/dda27da2-ea28-11e6-9457-3015d026f884.jpg)

So there's a big yellow button which, if you press it, will reuse the previous payment method. Below it there's a smaller button that's showing the last used payment method info, and the idea is that if you press that, you can change the payment method - it opens your DropIn:

![payment-second_payment-dropin](https://cloud.githubusercontent.com/assets/1850452/22595701/e9e71e38-ea28-11e6-8c40-373d010a4477.jpg)

The problem is that, if the user selects Android Pay from this screen, it again executes the payment with the previously used CC through Android Pay.

We have previously discussed this with the support via email (ticket #1339223), where they suggested we check PM nonces manually using `DropInResultListener.onResult()` when calling `DropInResult.fetchDropInResult`, like explained in your [docs](https://github.com/braintree/braintree-android-drop-in#fetch-last-used-payment-method), and if we encounter any Android Pay nonces we should then show the Android Pay selection screen.

The only method we found in your DropIn library for showing the Android Pay selection screen is `AndroidPay.changePaymentMethod(final BraintreeFragment fragment, final AndroidPayCardNonce androidPayCardNonce)` which explicitly requires `AndroidPayCardNonce` and crashes if it's null, while your `DropInResult` doesn't give `AndroidPayCardNonce` ever, always giving `null`.

Can you advise on how we could resolve this problem?

**Comment by lkorth** [comment]
@mrsasha the [README.md](https://github.com/braintree/braintree-android-drop-in#fetch-last-used-payment-method) has been updated to further clarify the case for Android Pay. 

It sounds like you've set up [preauths for Android Pay](https://developers.google.com/android-pay/preauth). In that case after you call `DropInResult#fetchDropInResult` and get back an Android Pay payment method, you will always need to call `AndroidPay#requestAndriodPay`. This will get you an `AndroidPayCardNonce` which you can then use with `AndroidPay#chagePaymentMethod` if the user wants to use an alternate card with Android Pay.

**Comment by mrsasha** [comment]
@lkorth thanks for this, I'm closing the issue then!
