### ISSUE TITLE
Maestro starting with 5043 not accepted

### ISSUE THREAD

**Issue by FrancescoBarrile** [braintree/braintree-android-drop-in#212]
### General information

* SDK/Library version:  5.1.0
* Environment: Production
* Android Version and Device: ALL

### Issue description

Maestro starting with 5043 ****, is not detected and not accepted.

**Comment by sshropshire** [comment]
Hello @FrancescoBarrile thank you for using the Braintree SDK for Android. We are looking into this issue.

**Comment by FrancescoBarrile** [comment]
@sshropshire Thank you, do you have any news?

**Comment by sshropshire** [comment]
Hi @FrancescoBarrile we have a fix merged into our underlying [android-card-form](https://github.com/braintree/android-card-form/pull/105) library. It will be in our next release of `braintree-android-drop-in`.

**Comment by sarahkoop** [comment]
This has been released in Drop-In [5.2.0](https://github.com/braintree/braintree-android-drop-in/releases/tag/5.2.0)
