### ISSUE TITLE
Android resource linking failed failed due to Braintree Library Update

### ISSUE THREAD

**Issue by Chamikacp** [braintree/braintree-android-drop-in#214]
I have added the implementation 'com.braintreepayments.api:drop-in:5.1.0' in build gradle file and also followed the following web site and did as it says.

https://developers.braintreepayments.com/guides/3d-secure/migration/android/v3#update-your-sdk-version

Now when I try to build the Android app it says
Android resource linking failed
\build\intermediates\merged_manifests\baseOrderDebug\AndroidManifest.xml:49: error: unexpected element <queries> found in <manifest> .

This is what in line 49 - 

    <queries>
        <intent>
            <action android:name="android.intent.action.VIEW" />

            <category android:name="android.intent.category.BROWSABLE" />

            <data android:scheme="https" />
        </intent>
    </queries>

Please help me to fix this issue. Thank you!

**Comment by sarahkoop** [comment]
Hi @Chamikacp, thanks for using the Braintree Android Drop In SDK. Support for Android 11 was added in versions `5.0.0` and later of Drop In, and upgrading your Android Gradle plugin to `4.1+` may resolve this issue. This [Google blog post](https://android-developers.googleblog.com/2020/07/preparing-your-build-for-package-visibility-in-android-11.html) provides an explanation of the changes.
