### ISSUE TITLE
Missing permissions for Google Play Services disable BraintreeFragment

### ISSUE THREAD

**Issue by mrsasha** [braintree/braintree-android-drop-in#22]
Hi,

we've gotten reports from some of our users that they get the `com.braintreepayments.api.exceptions.GoogleApiClientException: Connection failed: 19` error when they try to use the Braintree drop-in in our app. 

This is the `[SERVICE_MISSING_PERMISSION` error code](https://developers.google.com/android/reference/com/google/android/gms/common/ConnectionResult#SERVICE_MISSING_PERMISSION), and apparently it shows up because the users disabled some of the play services permissions, and for that reason, google api client listener throws an exception which gets propagated immediately and effectively renders the whole BraintreeFragment unusable. It looks like the situation described [in this article](http://jeremie-martinez.com/2017/02/08/firebase-permissions/?utm_source=androiddevdigest).

But, since this check is used only to ascertain the availability (or not) of Android Pay, I would rather like that that would be the outcome i.e. instead of propagating the `GoogleApiClientException` (or any `GoogeApiClient` errors, for that matter), it could just disable AndroidPay, and the credit card and PayPal would remain usable as payment methods. Currently, when opening the Drop In, I immediately get back `onActivityResult()` with `resultCode = 1`, which is not ideal.

**Comment by lkorth** [comment]
@mrsasha Thanks for the report and information! We have a fix that will go into the next release.

**Comment by mrsasha** [comment]
Hi, any info on the ETA of the next release?

**Comment by lkorth** [comment]
Thanks for your patience @mrsasha, we have been waiting on another change in https://github.com/braintree/braintree_android. This fix will go out this week.

**Comment by mrsasha** [comment]
cool, thanks!

**Comment by lkorth** [comment]
The fix for this was released in 3.0.7
