### ISSUE TITLE
Could not find com.braintreepayments.api:braintree:4.1.0 while building drop in 5.2.1

### ISSUE THREAD

**Issue by kamiljeglikowski** [braintree/braintree-android-drop-in#238]
### General information

* SDK/Library version: 5.2.1
* Environment: all
* Android Version and Device: all

### Issue description

After updating drop-in library version to from 3.7.1 to 5.2.1 I am experiencing this issue while building application
```
Could not find com.braintreepayments.api:braintree:4.1.0.
     Required by:
         project x  > com.braintreepayments.api:drop-in:5.2.1
         
 ```
 
 Previously I had version 3.7.1 and building worked fine.
 
 Can you please let me know what may be the issue here?

**Comment by sshropshire** [comment]
Hi @kamiljeglikowski thanks for using the Braintree SDK for Android. I'm a bit confused here, version `5.2.1` of `drop-in` is linked to version `3.15.0` of `braintree_android`. Can you post a snippet of your Gradle file where you're adding dependencies?

**Comment by mzubair2191** [comment]
I'm receiving a similar error:
> Could not resolve all files for configuration ':app:developDebugRuntimeClasspath'.
   > Could not resolve org.jfrog.cardinalcommerce.gradle:cardinalmobilesdk:2.2.4-1.
     Required by:
         project :app > com.braintreepayments.api:drop-in:5.2.1 > com.braintreepayments.api:three-d-secure:3.15.0
      > Could not resolve org.jfrog.cardinalcommerce.gradle:cardinalmobilesdk:2.2.4-1.
         > Could not get resource 'https://cardinalcommerce.bintray.com/android/org/jfrog/cardinalcommerce/gradle/cardinalmobilesdk/2.2.4-1/cardinalmobilesdk-2.2.4-1.pom'.
            > Could not GET 'https://cardinalcommerce.bintray.com/android/org/jfrog/cardinalcommerce/gradle/cardinalmobilesdk/2.2.4-1/cardinalmobilesdk-2.2.4-1.pom'. Received status code 403 from server: Forbidden`
