### ISSUE TITLE
Drop-in support samsung pay button

### ISSUE THREAD

**Issue by sajid-ivl** [braintree/braintree-android-drop-in#239]
### General information

* SDK/Library version: 5.+
* Braintree: 3.+
* Environment: Sandbox
* Android Version and Device: Samsung Galaxy S9
### Issue description

Braintree v3.+ supports samsung pay, even cant see samsung pay button on dropin ui
Does dropin supports samsung pay with ver. lib. 5.+?

**Comment by sarahkoop** [comment]
Hi @sajid-ivl - thanks for using the Braintree Android Drop In SDK.  The Drop In SDK does not currently support Samsung Pay. You can use `v3` of the Braintree Android SDK and `v2` of the Braintree Android Samsung Pay SDK to offer Samsung Pay. See our [developer docs](https://developer.paypal.com/braintree/docs/guides/samsung-pay/client-side) for more information.
