### ISSUE TITLE
Drop-in UI with recent payments

### ISSUE THREAD

**Issue by bkpratt84** [braintree/braintree-android-drop-in#24]
Does the drop-in UI V3 still show the recent payment methods like shown in the screen shot provided in the Read-me?

(Sandbox)
I created a new customer, generated a client token using the customerId, display the drop-in UI and generate a nonce using a test CC and created a transaction.sale passing the customerId, payment nonce and using the storeInVault option.

However, when displaying the drop-in UI again, it does not show the recent payment method.

If I view the customer in the vault via the control panel, I can see the payment method associated to the customer.

**Comment by lkorth** [comment]
Yes, all versions of v3 show vaulted payment methods if the user has them.

You should be seeing the vaulted payment method in Drop-in if your client token contains a customer id. You can also try [manually fetching the last used/default payment method](https://github.com/braintree/braintree-android-drop-in#fetch-last-used-payment-method) as it should be returned there as well. If neither of these are showing vaulted payment methods, ensure that you are generating a client token with the same customer id that the payment methods were vaulted on. If that doesn't work it may be easiest to contact support@braintreepayments.com so you can supply a client token and debug it further. Using the demo app in this repo I am unable to reproduce this issue.

**Comment by bkpratt84** [comment]
Thanks for responding. I figured out what my issue was. I was using GET instead of POST. Now it works as it should!

**Comment by lkorth** [comment]
Were you attempting to use a blank client token as a result of that then?

**Comment by bkpratt84** [comment]
I was using a GET request so I was actually passing a null customerId to the generateToken method since I was trying to retrieve the customerId via the req.body and not as a url parameter. So I switched to a post request and it worked as it should.
