### ISSUE TITLE
ZIP Code software keyboard

### ISSUE THREAD

**Issue by jagloro** [braintree/braintree-android-drop-in#25]
### General information

* SDK/Library version: 3.03 
* Environment: Both
* Android Version and Device: Samsung S6 Edge on Marshmallow

### Issue description

When adding a new card in the drop-in ui, after clicking on the zip field, I'm presented with a text keyboard instead of a number pad.  Why is that?

**Comment by lkorth** [comment]
Several countries, including Canada, the UK and the Netherlands all have alphanumeric postal codes.

**Comment by jagloro** [comment]
Didn't know that! Thanks!

**Comment by lkorth** [comment]
We've considered build a custom numeric input that allows an easy switch to an alphanumeric keyboard, but it's not something we've gotten to yet. Thanks for the feedback!
