### ISSUE TITLE
DropInRequest doesn't loading Braintree screen only after application install and first launch

### ISSUE THREAD

**Issue by anton-lazarchenko** [braintree/braintree-android-drop-in#251]
### General information

* SDK/Library version: 5.2.0 ('com.braintreepayments.api:drop-in:5.2.0')
* Environment: Sandbox, Production
* Android Version and Device: samsung galaxy s8+ (SM-G955F)

### Issue description
After first pure install of app (happens everytime) and after reinstall app via Android Studio (happens random and seldom) braintree screen doen't loading, only infinite circle progress visible.
After pressing devices back button and launch it again - everything works perfectly.

Token data always available while debugging issue.
I'm using this code to run braintree.

```
`        val dropInRequest = DropInRequest()
                .tokenizationKey(token)
                .disablePayPal()
                .disableVenmo()
                .disableGooglePayment()
        val intent: Intent = Intent(requireContext(), AddCardActivity::class.java)
                .putExtra(DropInRequest.EXTRA_CHECKOUT_REQUEST, dropInRequest)
        Timber.d { "====DROP" }
        Timber.d { token }
        startActivityForResult(intent, ADD_CARD_ACTIVITY_REQUEST)`
```

Seems like it is a bug, but if not - thanks in advance for any help with this!

**Comment by sarahkoop** [comment]
Hi @anton-lazarchenko thanks for using the Braintree Android Drop-in SDK.  I haven't been able to reproduce this behavior, but on initial investigation, it seems like it could be related to launching `AddCardActivity` directly rather than `DropInActivity`. Do you see the same behavior if you use `dropInRequest.getIntent()` in `startActivityForResult` rather than the intent created above?

**Comment by anton-lazarchenko** [comment]
> dropInRequest.getIntent(this)

Thank you for reply. I tried this but I've got the same behavior - only second launch works.

**Comment by anton-lazarchenko** [comment]
Issue might be closed, bug appears because of used BraintreeFragment before running AddCardActivity.
