### ISSUE TITLE
Migratation to Gradle plugin 7.0 needed

### ISSUE THREAD

**Issue by Neo-Turak** [braintree/braintree-android-drop-in#258]
there is an issue after upgrade the AGP version from 4.2.2 to 7.0.0, including Gradle version 6.7.1 to version 7.0.0.

the error message is:
Could not HEAD 'https://dl.bintray.com/thelasterstar/maven/org/jfrog/cardinalcommerce/gradle/cardinalmobilesdk/2.2.4-1/cardinalmobilesdk-2.2.4-1.pom'. Received status code 403 from server: Forbidden
Disable Gradle 'offline mode' and sync project

Even disable Gradle offline mode, it did not work.
the configuration is :
  maven {
            url "https://cardinalcommerce.bintray.com/android"
            credentials {
                username 'braintree-team-sdk@cardinalcommerce'
                password '******************************************'
            }
        }

//also this part is included.
        components.all {
            allVariants {
                withDependencies { deps ->
                    deps.each { dep ->
                        if (dep.group == 'net.minidev' && dep.name =='json-smart') {
                            dep.version {
                                prefer "2.3"
                            }
                            dep.because "resolving dependencies issue"
                        }
                    }
                }
            }
        }

it is highly recommended to upgrade by Android Studio Arctic Fox | 2020.3.1

**Comment by sarahkoop** [comment]
Hi @Neo-Turak thanks for using the Braintree Android Drop In SDK. The credentials for accessing the Cardinal Mobile SDK have been updated.  Please see #249 for the updated credentials to resolve this issue.
