### ISSUE TITLE
Question: "Kount Merchant Id"

### ISSUE THREAD

**Issue by Duoblood** [braintree/braintree-android-drop-in#26]
Hi ! 
How can I set my Kount Merchant Id when open dorp-in ?

**Comment by lkorth** [comment]
The Kount merchant id is automatically set in Drop-in based on how your fraud tools are configured with Braintree. If you are using the Kount Standard integration or the Kount Custom integration, Drop-in should use your Kount merchant id correctly. The only time it wouldn't work is if you were trying to use a different merchant id than the one configured with Braintree.

**Comment by Duoblood** [comment]
@lkorth Thanks for quick feedback.
We have solved this problem.  It was in the settings...
