### ISSUE TITLE
No way to disable PayPal using DropInRequest

### ISSUE THREAD

**Issue by mrsasha** [braintree/braintree-android-drop-in#27]
### General information

* SDK/Library version: 3.0.6
* Environment: all
* Android Version and Device: doesn't matter

### Issue description

Hi, I've tried using the `DropInRequest.disablePaypal()` method but it does nothing, and looking through the code of the `SupportedPaymentMethodsAdapter`, it's just checking the `Configuration` to see if Paypal is enabled, but the explicit flag passed in `DropInRequest` is not used.

**Comment by lkorth** [comment]
Thanks for the report @mrsasha. It is indeed being ignored, as is the option to disable Venmo. We'll fix it and release it shortly.

**Comment by lkorth** [comment]
The fix for this was released in 3.0.7
