### ISSUE TITLE
Sandbox certificate issues.

### ISSUE THREAD

**Issue by buticm** [braintree/braintree-android-drop-in#312]
### General information

* SDK/Library version: 4.8.0
* Environment: Sandbox
* Android Version and Device: Google Pixel 4a 5G with Android 12, Emulator for Pixel 2 with Android 10.

### Issue description

Demo app fails when trying to add new credit card `4111 1111 1111 1111`.
The error message is `java.security.cert.CertPathValidatorException: Trust anchor for certification path not found`.

It seems that the issue with the certificate that is served from the sandbox server `payments.sandbox.braintree-api.com`.
The connection from the browser to that server works fine and shows no issues with certificate.
However, the connection from the app fails.

Maybe the issue can be resolved by adding the certificate to trusted certificates of the app.
However, it would be preferable if the certificate for that server is updated on the server side to include most up to date CA root certificates.

Note, that the issue is intermittent. It's possible that only one/few of the servers serve incorrect certificate.

**Comment by sshropshire** [comment]
This should now be resolved. We had an SSL issue that temporarily affected our sandbox environment last week.
