### ISSUE TITLE
clientToken and tokenizationKey is not in DropInRequest

### ISSUE THREAD

**Issue by Ashish-jangir** [braintree/braintree-android-drop-in#316]
### General information

* SDK/Library version: 6.0.0
* Environment: Sandbox
* Android Version and Device: pixel 5 Api 28 Amulator, android 9

### Issue description

I am using SDK 6.0.0 (implementation 'com.braintreepayments.api:drop-in:6.+'). I can't find clientToken and tokenizationKey in DropInRequest(). So what should i do or what is the alternative of it? It was in the earilier version of the SDK like 5.
![Screenshot 2021-12-01 224208](https://user-images.githubusercontent.com/49928248/144281079-140afd91-4782-44e7-8fcc-d1a6469987d3.png)

**Comment by sshropshire** [comment]
Hi @Ashish-jangir thanks for using the Braintree SDK for Android. Client Token / Tokenization Key are now set via the constructor for `DropInClient` in `v6`. We removed them from `DropInRequest` to separate DropIn auth and configuration components.

**Comment by sshropshire** [comment]
@Ashish-jangir also here's a link to our [MIGRATION_GUIDE](https://github.com/braintree/braintree-android-drop-in/blob/master/v6_MIGRATION_GUIDE.md#launch-drop-in) detailing these changes.
