### ISSUE TITLE
 java.lang.NullPointerException:BottomSheetPresenter.unbind()

### ISSUE THREAD

**Issue by Yongyong-Zhou** [braintree/braintree-android-drop-in#319]
This is how to test the demo application:

![image](https://user-images.githubusercontent.com/86334406/145172551-987c752e-d97b-4e27-8883-0dcb4796d273.png)
![image](https://user-images.githubusercontent.com/86334406/145172583-cb023924-e3c8-4061-8d92-11602f1cf9d3.png)

The phone turns on automatic rotation, enters the credit or debit card input page, crashes after the horizontal screen, and exits.
It seems to appear every time.

Logcat Output:
![image](https://user-images.githubusercontent.com/86334406/145172426-97645e66-9a95-4c91-8826-55248cd70a04.png)
 
This is a video recorded:

https://user-images.githubusercontent.com/86334406/145173579-daaa7af4-9f2c-48bb-ba99-6dabc39f8141.mp4

**Comment by Yongyong-Zhou** [comment]
This is my demo:
MyApplication32.zip

**Comment by sshropshire** [comment]
@Yongyong-Zhou thanks for using the Braintree SDK for Android. We'll take a look at this and once we're able to reproduce we'll provide a fix.

**Comment by sshropshire** [comment]
This is now resolved in version [6.0.1](https://github.com/braintree/braintree-android-drop-in/releases/tag/6.0.1)

**Comment by Yongyong-Zhou** [comment]
> 现在在[6.0.1](https://github.com/braintree/braintree-android-drop-in/releases/tag/6.0.1)版中解决了这个问题[](https://github.com/braintree/braintree-android-drop-in/releases/tag/6.0.1)

Thank you very mush, Because the 6.XX version now seems to be in Beta, if there is an official version to solve this problem, please trouble me, I will upgrade the braintree version immediately.

**Comment by sshropshire** [comment]
@Yongyong-Zhou 6.X is out of beta and is generally available. [6.0.1](https://github.com/braintree/braintree-android-drop-in/releases/tag/6.0.1) is the latest release and contains a fix for this issue.

**Comment by Yongyong-Zhou** [comment]
@sshropshire Excuse me, I want to ask a question:
I have integrated the implementation of 'com.braintreepayments.api:drop-in:6.0.1', but we need to make paypal a separate button for users to operate, now only after clicking the payment button in braintree-android-drop-in -Select Paypal in the pop-up window, can you tell me the steps to call paypal directly? Or is there a direct call to paypal demo?

If I want to do this function, I have already referenced the drop-in dependent library, do I need to introduce the Paypal dependent library separately?

Thank you


https://github.com/braintree/braintree-android-drop-in/issues/327
