### ISSUE TITLE
Sensitive data in memory

### ISSUE THREAD

**Issue by Pirokar** [braintree/braintree-android-drop-in#322]
### General information

* SDK/Library version: 5.x version, 6.0.1
* Environment: both
* Android Version and Device: all devices

### Issue description

Our application was found to store the credit or debit card number, expiry date and CVV in memory after the initial card registration for the entire period that the application was running thereafter.  After exiting and re-starting the application, the data was no longer found in memory.  I downloaded the demo project with the latest library (6.0.1), made a memory dump after registering the card and returning back to the main screen in the demo project, and the dump has all the data - the card number, cvv code, expiration date, and so on. The same situation with previous version too - with the latest 5.x version. In the memory dump, you can see that the credit card number is stored in several memory areas This still could present a risk where this was running on a rooted device, and a malicious application was monitoring memory for stored card data. Please see an example in the memory dump (test card): 
`"operationName":"TokenizeCreditCard","variables":{"input":{"options":{"validate":true},"creditCard":{"number":"5105105105105100","expirationMonth":"08","expirationYear":"24","cvv":"200","billingAddress":{"postalCode":"347900"}}}}}   `

**Comment by sshropshire** [comment]
Hi @Pirokar thanks for using the Braintree SDK for Android. We've addressed this in our core SDK [here](https://github.com/braintree/braintree_android/pull/486). Once we get everything reviewed and merged, we'll update DropIn.

**Comment by Pirokar** [comment]
@sshropshire Is it already fixed? If yes, on which versions? Will be cool to see this fix not only in the latest version, maybe in the previous 3.x too

**Comment by sshropshire** [comment]
@Pirokar it'll be in our next release once DropIn references the latest Core version with the changes.

**Comment by Pirokar** [comment]
@sshropshire what about fix fir 5.x or 4.x version? Will it be available?

**Comment by sshropshire** [comment]
@Pirokar this is something to consider, however it may be more difficult to do without introducing a breaking change to previous versions.

**Comment by Pirokar** [comment]
@sshropshire but you have a table [here](https://github.com/braintree/braintree-android-drop-in), that said, that even old 4.x version should be supported until September 2022. You have a really dangerous bug in this versions, shouldn't you fix it in older versions according to your own table?

**Comment by Pirokar** [comment]
@sshropshire any comments?

**Comment by sshropshire** [comment]
@Pirokar we do have a [deprecation policy](https://developer.paypal.com/braintree/docs/guides/client-sdk/deprecation-policy#status-deprecated) in place stating that we perform updates on the latest major version. In this particular instance, to back port this functionality we would have to make several breaking changes. We refactored our SDK for `v4` to leverage package private and it's the primary reason we were able to provide this update in a `patch` version. I would suggest updating to the latest version of the SDK.

**Comment by sshropshire** [comment]
@Pirokar correct for DropIn but the [core SDK](https://developer.paypal.com/braintree/docs/guides/client-sdk/deprecation-policy#status-deprecated) is the fundamental piece that has been deprecated.

**Comment by Pirokar** [comment]
@sshropshire  but it will be unsupported inly from June 2022. Why you can't provide the fix for this version, if it still supported?

**Comment by sshropshire** [comment]
@Pirokar is it possible for your app to upgrade to the latest [6.0.2](https://github.com/braintree/braintree-android-drop-in/blob/master/v6_MIGRATION_GUIDE.md) version?

**Comment by Pirokar** [comment]
@sshropshire possible, but it's really complicated. We have a huge code base. Thats why I'm asking

**Comment by sshropshire** [comment]
@Pirokar is there anything in the existing API that makes it a challenge? We've recently received some feedback and are working to make integration simpler and more flexible. We have an internal solution but we're finalizing the surface of the API. You can see some of the discussion [here](https://github.com/braintree/braintree_android/discussions/496).

**Comment by Pirokar** [comment]
You're removed drop-in requests. We're using it in many places

**Comment by sshropshire** [comment]
We still have [DropInRequest](https://github.com/braintree/braintree-android-drop-in/blob/master/Drop-In/src/main/java/com/braintreepayments/api/DropInRequest.java) in the latest version.

**Comment by Pirokar** [comment]
@sshropshire Hi. Please help with migration to Drop-In v6.
I have this class from old version:

import androidx.appcompat.app.AppCompatActivity
import com.braintreepayments.api.BraintreeFragment
import com.braintreepayments.api.ThreeDSecure
import com.braintreepayments.api.models.ThreeDSecureRequest
import com.ocado.mobile.android.annotation.OpenForTesting

interface BraintreeThreeDsHandlerInt {
    fun newInstance(activity: AppCompatActivity, token: String): BraintreeFragment
    fun performVerification(fragment: BraintreeFragment, request: ThreeDSecureRequest)
}

@OpenForTesting
class BraintreeThreeDsHandler() : BraintreeThreeDsHandlerInt {

    override fun newInstance(activity: AppCompatActivity, token: String): BraintreeFragment {
        return BraintreeFragment.newInstance(activity, token)
    }

    override fun performVerification(fragment: BraintreeFragment, request: ThreeDSecureRequest) {
        ThreeDSecure.performVerification(fragment, request) { request, lookup ->
            if (fragment.isActive) {
                ThreeDSecure.continuePerformVerification(fragment, request, lookup)
            }
        }
    }
}
How to migrate it to v6?

**Comment by sarahkoop** [comment]
Hi @Pirokar - Please check out our [v6 migration guide](https://github.com/braintree/braintree-android-drop-in/blob/master/v6_MIGRATION_GUIDE.md), it should contain the info you need to upgrade! Additionally, requesting 3DS verification outside of Drop-in is not required - 3DS will be requested through Drop-in if a `ThreeDSecureRequest` with an `amount` is set on `DropInRequest` and your merchant account is configured for 3DS.
