### ISSUE TITLE
Avoid PayPal Vaulting

### ISSUE THREAD

**Issue by kiwi4747** [braintree/braintree-android-drop-in#332]
### General information

* SDK/Library version: 6.0.2
* Environment: Both
* Android Version and Device: Any

### Issue description

Is it possible to add the option to disable only PayPal vaulting in the DropInRequest? We need it for legal reasons.

**Comment by sarahkoop** [comment]
You can set a `PayPalCheckoutRequest` as the `payPalRequest` on your `DropInRequest` to use the checkout flow rather than the vault flow. If you do not set the `payPalRequest`, it will default to a vault flow.
