### ISSUE TITLE
Option to not retrieve only PayPal vaulted

### ISSUE THREAD

**Issue by kiwi4747** [braintree/braintree-android-drop-in#333]
### General information

* SDK/Library version: 6.0.2
* Environment: both
* Android Version and Device: Any

### Issue description

Is it possible to add the option to not retrieve only PayPal vaulted payment method in the DropInRequest? 
We use the same Drop-in in two different flows, in one of those, we should not save nor retrieve vaulted PayPal (the user has to log in every time, for legal reasons), in the other one we don't want to lose the feature.
Thank you :)

**Comment by sarahkoop** [comment]
Hi @kiwi4747 - Are you launching the Drop-in with the same `DropInRequest` for each flow?  To specify different PayPal vaulting options, you would need to launch the Drop-in with different `DropInRequest` objects, where you specify the specific PayPal options for that Drop-in flow through the `PayPalRequest` on the `DropInRequest`.

**Comment by sarahkoop** [comment]
Closing this as resolved. Please feel free to re-open if the information provided did not solve your issue.
