### ISSUE TITLE
SSLProtocolException

### ISSUE THREAD

**Issue by crocoM4** [braintree/braintree-android-drop-in#34]
### General information

* SDK/Library version: com.braintreepayments.api:drop-in:3.0.8
* Environment:  Sandbox
* Android Version and Device: Samsung gt - s7390 with Android 4.1 API 16

### Issue description

I tried to add the Drop-in UI in my android application but i get the following exception:

> com.braintreepayments.api.exceptions.ConfigurationException: Request for configuration has failed: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x506cbae0: Failure in SSL library, usually a protocol error
error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure (external/openssl/ssl/s23_clnt.c:744 0x4bf22814:0x00000000). Future requests will retry up to 3 times

Here's my code.

On button Click event:

```
public void showDropInUI(View view) {
        DropInRequest dropInRequest = new DropInRequest()
                .clientToken(clientToken) ;
        
        startActivityForResult(dropInRequest.getIntent(context), DROP_IN_REQUEST);
} 

```
```
public void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        if (requestCode == DROP_IN_REQUEST) {
            if (resultCode == Activity.RESULT_OK) {
                DropInResult result = data.getParcelableExtra(DropInResult.EXTRA_DROP_IN_RESULT);
                String paymentMethodNonce = result.getPaymentMethodNonce().getNonce();
                // send paymentMethodNonce to your server
            } else if (resultCode == Activity.RESULT_CANCELED) {
                // canceled
            } else {
                // an error occurred, checked the returned exception
                Exception exception = (Exception) data.getSerializableExtra(DropInActivity.EXTRA_ERROR);
            }
        }
}
```

I get the clientToken from my server method.

I try to use the Tokenization Key, insted of the clientToken, but i get the same error.

Am i missing something? Sorry for my english.

**Comment by sdcoffey** [comment]
Hey @crocoM4,

Thanks for opening this issue. We're aware of issues with the SSL implementation on that particular Samsung device that will prevent the device from communicating with Braintree's servers. Note also that later this year, Braintree will be completely dropping support for all security protocols lower than TLS 1.2, as required by PCI regulations. See [this article](https://blog.pcisecuritystandards.org/migrating-from-ssl-and-early-tls) for more information on the industry's transition to newer security protocols. Would you mind trying your integration on a newer device or emulator and letting us know if you're still experiencing issues?

**Comment by crocoM4** [comment]
Hi @sdcoffey,
thanks for reply.
I have test my app on a THL T6C Android 5.1 API 22 and it work.
I try even on a Samsung S4 Android 4.4.2 API 19 and it worked but, i think, because that device is rooted, maybe on other API 19 device it doesn't work.

In [ android documentation](https://developer.android.com/reference/javax/net/ssl/SSLSocket.html) said that the TLS 1.2 is supported by 16+ API device but is enable by default from API 20+ .

I search a method to enable it and i fonud [this solution](https://github.com/square/okhttp/issues/2372#issuecomment-244807676) , create a custom SSLSocketFactory and than pass to a OkHttpClient.

There is a possibilty to integrate that method and make calls to  Braintree's servers?

There is any a workaround to make it work?

**Comment by lkorth** [comment]
The SDK has had [TLS 1.2 enabled on API 16-19 devices](https://github.com/braintree/braintree_android/blob/03a5b69d08c0e11cf6a8f52c397b3d682823a7ac/Core/src/main/java/com/braintreepayments/api/internal/TLSSocketFactory.java#L117) for quite some time.

We've heard of this issue occurring on a very small number of devices, but have never been able to get a device that reproduces this. We suspect an implementation bug on the devices that always tries to use SSLv3 and won't fallback to other methods if the server does not support SSLv3. 

As a quick test, if you put this code in your app and run it on the Samsung S7390 that is currently returning the error you should get some log output that may be useful in tracking this down.

```java
try {
    SSLContext sslContext = SSLContext.getInstance("TLS");
    sslContext.init(null, null, null);
    SocketFactory socketFactory = sslContext.getSocketFactory();

    String[] supportedProtocols = ((SSLSocket) socketFactory.createSocket()).getSupportedProtocols();
    for (String protocol : supportedProtocols) {
        Log.d("SSL-TEST", "Supported SSL protocol: " + protocol);
    }
} catch (Exception e) {
    Log.d("SSL-TEST", e.getMessage());
}
```

**Comment by crocoM4** [comment]
Hi @lkorth 
i put your code in my MainActivity in the onCreate method.
here the log that i get:

> 05-04 17:30:10.384 5795-5795/com.example.prova D/SSL-TEST: Supported SSL protocol: SSLv3
> 05-04 17:30:10.384 5795-5795/com.example.prova D/SSL-TEST: Supported SSL protocol: TLSv1
> 05-04 17:30:10.384 5795-5795/com.example.prova D/SSL-TEST: Supported SSL protocol: TLSv1.1
> 05-04 17:30:10.384 5795-5795/com.example.prova D/SSL-TEST: Supported SSL protocol: TLSv1.2

if you need more tests or info just let me know.

Thanks for the reply and the explanations

**Comment by crocoM4** [comment]
After a lot of search i found a solution that worked for me, in my code i added this:

`ProviderInstaller.installIfNeeded(getApplicationContext());`

here [google documentation](https://developers.google.com/android/reference/com/google/android/gms/security/ProviderInstaller) 

For now I' dont get the exception and the drop-in ui work just fine.

**Comment by lkorth** [comment]
Thanks for sharing your fix!

It sounds like this may be similar to paypal/PayPal-Android-SDK#341 and something in Google Play services is swapping the SSL implementation. Calling `ProviderInstaller#installIfNeeded` may be resetting it.
