### ISSUE TITLE
No result on user dismiss

### ISSUE THREAD

**Issue by paolomanca** [braintree/braintree-android-drop-in#346]
### General information

* SDK/Library version: 6.1.0
* Environment: sandbox
* Android Version and Device: any

### Issue description
On version 6.1.0 I don't receive any result when the user dismisses the drop in.
I think the intended behaviour was to return a `DropInResult` with `UserCanceledException` from `DropInListener#onDropInFailure`. However, in `DropInActivityResultContract#parseResult` this logic is conditioned to `
intent != null`, which is always false for `RESULT_CANCELED`, leading to no result being produced.

**Comment by sshropshire** [comment]
@paolomanca thanks for using the Braintree SDK for Android and for filing this bug! This is a great catch, there was an oversight with the unit test scaffolding. We've created a PR and hope to have this fix out soon.

**Comment by paolomanca** [comment]
Hi @sshropshire, do you have an ETA for a release?
