### ISSUE TITLE
Show message when fake card number is entered and pressed "ADD CARD" button.

### ISSUE THREAD

**Issue by championboylay** [braintree/braintree-android-drop-in#36]
### General information
* Environment: Sandbox

### Issue description

I want to show message when I have submit the payment with fake card number (I have generated via http://www.getcreditcardnumbers.com). 
![image 2](https://cloud.githubusercontent.com/assets/2637794/25791061/be4426e0-33e3-11e7-8d70-ed07b7f6985f.jpg)

**Comment by sdcoffey** [comment]
Hey @championboylay,

Thanks for the suggestion. Can you explain the motivation for this, or why showing a toast message when you know you're using a generated credit card number would not suffice?

**Comment by championboylay** [comment]
### **Motivation**
When user inputs fake numbers, I just want to **give **feedback**** which they are entering the invalid numbers. 

At IOS, sdk responses "Card number invalid" when user submits with fake card numbers.

**Comment by sdcoffey** [comment]
I think there's some confusion about terms here, so to be clear, we make a distinction between what is a `fake` credit card number, what is `invalid`, and what is `valid`. In sandbox, we consider a `fake` card number to be a [known test number](https://developers.braintreepayments.com/reference/general/testing/ruby#credit-card-numbers) that is [luhn 10 valid](https://en.wikipedia.org/wiki/Luhn_algorithm), and an `invalid` number to be one that is either not luhn valid or not one of those known test numbers. In production, an `valid` number is one that is both luhn 10 valid, and issued by a bank, and which transactions may be run against.

When a user [enters their card number](https://github.com/braintree/android-card-form/blob/master/CardForm/src/main/java/com/braintreepayments/cardform/view/CardEditText.java#L107), we do this [luhn 10](https://github.com/braintree/android-card-form/blob/master/CardForm/src/main/java/com/braintreepayments/cardform/utils/CardType.java#L150-L168) check to ensure that the card number passes the luhn check. When the submits the card details in Drop-in, we [tokenize the card](https://github.com/braintree/braintree-android-drop-in/blob/master/Drop-In/src/main/java/com/braintreepayments/api/dropin/AddCardActivity.java#L309), the result of which will be a success if the card number is `valid` under the definition outlined above. 

This is a long-winded answer to your question, but what I'm getting at is that there's no way to know that a card is invalid, if it _also passes a luhn check_ until the user hits submit in Drop-in. Let me know if you're still confused, or if I'm confused about your issue. Thanks!

**Comment by championboylay** [comment]
Thanks for your detail explanation. I didn't know  luhn 10 before.
