### ISSUE TITLE
Bump Braintree dependency version to 4.18.0

### ISSUE THREAD

**Issue by joeboyscout04** [braintree/braintree-android-drop-in#366]
### General information

* SDK/Library version: 6.3.0
* Environment: Production
* Android Version and Device: All

### Issue description

We'd love to have a new version of Drop-in which bumps the Braintree dependency version to 4.18.0 to fix a [crash](https://github.com/braintree/braintree_android/issues/585#event-7625448033) with the Cardinal SDK dependency.   Thank you!

**Comment by sshropshire** [comment]
Hi @joeboyscout04 thanks for using the Braintree SDK for Android. We appreciate your patience. We're actively working on this and should have an update soon.

**Comment by jaxdesmarais** [comment]
Hey @joeboyscout04 -

This was just released in [version 6.4.0 of the Drop-in](https://github.com/braintree/braintree-android-drop-in/releases/tag/6.4.0) and includes the latest version of the Core SDK (4.19.0). If you run into issues updating please let us know.
