### ISSUE TITLE
Click on Drop In's Paypal icon Returns code Activity.RESULT_FIRST_USER (1) 

### ISSUE THREAD

**Issue by marcoalmeidap** [braintree/braintree-android-drop-in#37]
### General information

* SDK/Library version: 

Im using the following dependencies:

    compile 'com.braintreepayments.api:drop-in:3.0.8'
    compile 'com.google.android.gms:play-services-wallet:9.8.0'
    compile 'io.card:android-sdk:5.4.2'

* Environment: 

   Im using the Sandbox credentials.

* Android Version and Device: 

 Im testing in a Genymotion emulator: Google Galaxy Nexus - 4.3 - API 18 

* AndroidManifest

It includes the com.braintreepayments.api.BraintreeBrowserSwitchActivity and enables wallet.api as the demo does.

### Issue description

* When I click in the DropIn's Paypal icon, the next Activity is never showed and I received in the onActivityResult() method a result code of 1 (Activity.RESULT_FIRST_USER). Can you help me solving this issue ?

### IMPORTANT:  

I tested the Demo app and I don't have the same problem.

**Comment by lkorth** [comment]
If you look in the [README](https://github.com/braintree/braintree-android-drop-in#usage) there is documention for checking the error when the `resultCode` is not `Activity.RESULT_OK`. What is the exception you're getting back in `(Exception) data.getSerializableExtra(DropInActivity.EXTRA_ERROR);` when the result code is `Activity.RESULT_FIRST_USER`?

**Comment by marcoalmeidap** [comment]
I got this message error: onActivityResult:ERROR: Merchant account not found ...

I tested with the token published in the website and the error has gone. But I need to use the token generated by my Java server.

I realized that the token's length is different too. The generated token has less characters than the token mentioned earlier.

**Comment by marcoalmeidap** [comment]
Well, I read the mail that was sent to me when I created my Sandbox account and I realized that I didn't finish all steps. This was not a SDK issue.

Conclusion: For testing purposes it's better to use the token provided in your documentation.  

Thanks @lkorth u rock !
