### ISSUE TITLE
Drop-in UI still hangs when attempting to register a duplicate payment method.

### ISSUE THREAD

**Issue by soarb** [braintree/braintree-android-drop-in#370]
### General information

* SDK/Library version: com.braintreepayments.api:drop-in:6.4.0
* Environment: Sandbox
* Android Version and Device: Samsung Galaxy S10 with Android 12.0

### Issue description

I can confirm that the closed duplicate payment issue [here](https://github.com/braintree/braintree-android-drop-in/issues/357), is fixed, however, if the user attempts to navigate back to the root screen i.e., to select an alternative form of payment, the drop-in still hangs and displays a spinner which doesn't resolve.

The only way to continue, is to close the drop-in completely and re-launch it (which isn't immediately obvious without either tapping on the overlay OR using the soft navigation back button).

Please see the full [android experience](https://youtube.com/shorts/CLWonhW-GOc)

Any advice would be gratefully appreciated as always :)

Cheers!

Benj

**Comment by soarb** [comment]
Any update on this please?

**Comment by sshropshire** [comment]
Hey @soarb thanks for your patience on this issue. I'll pick this up and confirm to see what fix is needed. I should have more information soon.

**Comment by sshropshire** [comment]
@soarb a fix for this has been released in version [6.8.0](https://github.com/braintree/braintree-android-drop-in/blob/6.8.0/CHANGELOG.md#680).

**Comment by soarb** [comment]
@sshropshire thank you so much! ... all good with this latest release :)
