### ISSUE TITLE
6.5.1 PayPal not working

### ISSUE THREAD

**Issue by molchanovskiy** [braintree/braintree-android-drop-in#377]
PayPal always gives UserCanceledException and onDropInSuccess is never called.

```
        val dropInRequest = DropInRequest()
        dropInRequest.isVaultManagerEnabled = true
        val payPalRequest = PayPalVaultRequest()
        dropInRequest.payPalRequest = payPalRequest
        .......
        dropInClient.setListener(PaymentDropInListener())
        dropInClient.launchDropIn(dropInRequest)
```
Could you check what is wrong?

I had tested with PayPalClient and it works fine, the issue only exist when using DropInClient

**Comment by sshropshire** [comment]
Hi @molchanovskiy thanks for using the Braintree SDK for Android. Are you instantiating the `DropInClient` and setting its listener in your Activity / Fragment's `onCreate()` method?

**Comment by molchanovskiy** [comment]
@sshropshire 
Yes, credit card and google pay works great, the issue only occurs with PayPal.

**Comment by sshropshire** [comment]
A few questions:

- What version of Android does this occur on?
- Is this on a device or emulator?

Also, can you provide a video of the unexpected behavior so we can better assist with debugging?

**Comment by sshropshire** [comment]
@molchanovskiy this [integration pattern](https://github.com/braintree/braintree-android-drop-in/issues/374#issuecomment-1345929549) could cause unpredictable behavior.

**Comment by molchanovskiy** [comment]
@sshropshire 
PayPal works fine on device, thank you!

**Comment by sshropshire** [comment]
Awesome! Closing this for now. Feel free to reopen this if you encounter the issue again.

Going forward, if you'd like to share more about your use case, we are coming up on a `next-major-version`. We'll soon reopen [this discussion](https://github.com/braintree/braintree_android/discussions/496) to solicit feedback from the community on our API in an effort to offer the best possible developer experience.
