### ISSUE TITLE
Fix artifact dependency

### ISSUE THREAD

**Issue by consp1racy** [braintree/braintree-android-drop-in#38]
Dependency configuration of `drop-in` or `card-form` module forces consumers to use the latest available support library in range [25.0.0,26) completely ignoring that consumer only ever specified e.g. `25.1.0` in their `build.gradle` file.

[This SO question](http://stackoverflow.com/questions/42949974/android-support-repo-46-0-0-with-android-studio-2-3/42957234#42957234) describes what's happening.

The artifacts should only depend on the *oldest support lib they can do with*. Dependency resolution will automatically pick the newest of all specified versions in the project.

Current dependency graph:

```
+--- com.braintreepayments.api:drop-in:3.0.8
|    +--- com.braintreepayments.api:braintree:2.4.3 -> 2.5.2 (*)
|    +--- com.braintreepayments:card-form:3.0.5
|    |    \--- com.android.support:design:[25.0.0,25.99.0) -> 25.3.1 (*)
|    \--- com.android.support:cardview-v7:[25.0.0,25.99.0) -> 25.3.1 (*)
```

More info: 
https://docs.oracle.com/middleware/1212/core/MAVEN/maven_version.htm

**Comment by robertoestivill** [comment]
This is particularly annoying, as the builds become not deterministic. Sometimes we are not able to reproduce them, and lint errors crash builds whenever there's a new version of the library.

**Comment by lkorth** [comment]
Thanks for the report and links @consp1racy. You're right that this is the wrong way to do it, this is mostly legacy from very early SDK releases. It has been fixed in `android-card-form` and Drop-in and will go out in the next release.
