### ISSUE TITLE
multiple payment instance create if user quick tap on payment method list.

### ISSUE THREAD

**Issue by WishalKalkani** [braintree/braintree-android-drop-in#388]
multiple payment instance create if user quick tap on payment method list.
bellow i attached video. for better understand.
Can you please tell me if android side any listener where we can get callback if user click on payment method list item.
Thank you.

https://drive.google.com/file/d/14kO1igyuehLtv-MM45BhQ5o6q2TCxLYi/view?usp=drivesdk

**Comment by sshropshire** [comment]
Hi @WishalKalkani thanks for filing this issue. It's difficult to tell from the video what unexpected behavior is occurring. Would you mind detailing the steps to reproduce?

**Comment by hollabaq86** [comment]
Closing this issue since we haven't heard from OP in a few weeks.
