### ISSUE TITLE
No Error Displayed for Invalid Card on simplified AddCardActivity

### ISSUE THREAD

**Issue by WishalKalkani** [braintree/braintree-android-drop-in#389]
@braintreeps @bohford  @dpirotte @kcboschert @edebill @bluk 
I am not getting any callback or any error for invalid card.
card no. 4000 0000 0000 0341
i attached video for your reference.

[https://drive.google.com/file/d/1fDNQhr_Egfk6aNw49rzqTr_5FaJJFBAW/view?usp=share_link]

Hoping for your quick response.
Thank you.

**Comment by sshropshire** [comment]
Hi @WishalKalkani is this card from our [docs](https://developer.paypal.com/braintree/docs/) site? I noticed the card number is Luhn valid and I can confirm successful tokenization of the card in our Demo app.

**Comment by WishalKalkani** [comment]
@sshropshire card no. 4000 0000 0000 0341 not working in demo app too
please double check. and not throwing any error or any callback.
i already attach video  please check.
https://drive.google.com/file/d/1fDNQhr_Egfk6aNw49rzqTr_5FaJJFBAW/view?usp=share_link

**Comment by sshropshire** [comment]
@WishalKalkani this appears to be a [Stripe test card](https://stripe.com/docs/testing#declined-payments). Please test using one of the following [Braintree test cards](https://developer.paypal.com/braintree/docs/guides/credit-cards/testing-go-live/php) we have on our site. If you have any additional questions on test cards, please contact [Braintree Support](https://developer.paypal.com/braintree/help).
