### ISSUE TITLE
Android resources linking failed in Braintree Drop in implementation

### ISSUE THREAD

**Issue by sovoereign** [braintree/braintree-android-drop-in#391]
I have been using 'Braintree Drop-in' implementation in the project. After updating braintree gradel version, getting consistent issues I repeatedly tried the "Invalidated/restart" option and also deleted the cache folder. Links to resources are still not working.

issue below says bt_drop_in_activity_theme is not found in Drop-in library Ui.

`  /Users/.gradle/caches/transforms-3/aeebbaf73dd8bae1707a334da3b03cbb/transformed/jetified-drop-in-6.6.0/AndroidManifest.xml:16:9-29:20: AAPT: error: resource style/bt_drop_in_activity_theme (aka com.xxxxxx.userapp:style/bt_drop_in_activity_theme) not found.`

**Comment by sshropshire** [comment]
@sovoereign closing for now until we can get more details. I'd suggest updating to the latest and a clean build in the meantime. Feel free to re-open with an [issue template](https://github.com/braintree/braintree-android-drop-in/issues/new/choose) as mentioned by @scannillo.
