### ISSUE TITLE
Could not download cardinalmobilesdk-2.2.6-1.aar

### ISSUE THREAD

**Issue by surajappentus** [braintree/braintree-android-drop-in#400]
**Integration Details (please complete the following information):**

* SDK/Library version: 6.1.0
* Environment: Sandbox
* Android Version and Device: first of all not build the apk
* Braintree dependencies:

implementation 'com.braintreepayments.api:drop-in:6.1.0'

**Describe the bug**
I am trying to build project but showing in another system. It is working on a particular system which have already implemented this dependency since june 2022 in this project.

But not working in another system . I tried many solution but not worked.

Error :-
Could not resolve all files for configuration ':app:debugRuntimeClasspath'.> Failed to transform cardinalmobilesdk-2.2.6-1.aar (org.jfrog.cardinalcommerce.gradle:cardinalmobilesdk:2.2.6-1) to match attributes {artifactType=android-jni, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.> Could not download cardinalmobilesdk-2.2.6-1.aar (org.jfrog.cardinalcommerce.gradle:cardinalmobilesdk:2.2.6-1): No cached version available for offline mode

**To Reproduce**
getting error like this -> Could not download cardinalmobilesdk-2.2.6-1.aar

**Expected behavior**
It should be work every system where I build the project

**Screenshots**

![219361933-fca7f39b-273d-46e5-8e14-abfb362ec63a](https://user-images.githubusercontent.com/96175961/219652024-ced1933d-6462-4514-8f40-6391e7075d57.png)

**Comment by ShubhAppentus** [comment]
Gettng same issue please look into this @here

**Comment by surajappentus** [comment]
The latest version resolved the issue. It may be that version 6.1.0 was removed from the repository.
Thank you @sshropshire for your quick response.
