### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by ParbatFTX** [braintree/braintree-android-drop-in#407]
Executing tasks: [:app:clean, :app:assembleDebug] in project D:\MySambandh

> Task :app:clean UP-TO-DATE
> Task :app:preBuild UP-TO-DATE
> Task :app:preDebugBuild UP-TO-DATE
> Task :app:createDebugVariantModel
> Task :app:mergeDebugNativeDebugMetadata NO-SOURCE
> Task :app:compileDebugAidl NO-SOURCE
> Task :app:compileDebugRenderscript NO-SOURCE
> Task :app:generateDebugBuildConfig
> Task :app:checkDebugAarMetadata FAILED
> Task :app:generateDebugResValues
> Task :app:mapDebugSourceSetPaths FAILED
> Task :app:generateDebugResources
> Task :app:mergeDebugResources FAILED
> Task :app:packageDebugResources
> Task :app:createDebugCompatibleScreenManifests
> Task :app:extractDeepLinksDebug
> Task :app:processDebugMainManifest FAILED
> Task :app:javaPreCompileDebug
> Task :app:mergeDebugShaders
> Task :app:compileDebugShaders NO-SOURCE
> Task :app:generateDebugAssets UP-TO-DATE
> Task :app:mergeDebugAssets FAILED
> Task :app:processDebugJavaRes NO-SOURCE
> Task :app:checkDebugDuplicateClasses FAILED
> Task :app:desugarDebugFileDependencies FAILED
> Task :app:parseDebugLocalResources
> Task :app:mergeDebugJniLibFolders
> Task :app:mergeDebugNativeLibs FAILED
> Task :app:validateSigningDebug
> Task :app:writeDebugAppMetadata
> Task :app:writeDebugSigningConfigVersions

FAILURE: Build completed with 8 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.braintreepayments.api:drop-in:6.8.2-SNAPSHOT.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/maven-metadata.xml
       - https://dl.google.com/dl/android/maven2/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/drop-in-6.8.2-SNAPSHOT.pom
       - https://repo.maven.apache.org/maven2/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/maven-metadata.xml
       - https://repo.maven.apache.org/maven2/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/drop-in-6.8.2-SNAPSHOT.pom
       - https://jitpack.io/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/maven-metadata.xml
       - https://jitpack.io/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/drop-in-6.8.2-SNAPSHOT.pom
       - https://cardinalcommerceprod.jfrog.io/artifactory/android/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/maven-metadata.xml
       - https://cardinalcommerceprod.jfrog.io/artifactory/android/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/drop-in-6.8.2-SNAPSHOT.pom
     Required by:
         project :app
   > Could not find com.braintreepayments.api:drop-in:6.8.2-SNAPSHOT.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/maven-metadata.xml
       - https://dl.google.com/dl/android/maven2/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/drop-in-6.8.2-SNAPSHOT.pom
       - https://repo.maven.apache.org/maven2/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/maven-metadata.xml
       - https://repo.maven.apache.org/maven2/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/drop-in-6.8.2-SNAPSHOT.pom
       - https://jitpack.io/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/maven-metadata.xml
       - https://jitpack.io/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/drop-in-6.8.2-SNAPSHOT.pom
       - https://cardinalcommerceprod.jfrog.io/artifactory/android/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/maven-metadata.xml
       - https://cardinalcommerceprod.jfrog.io/artifactory/android/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/drop-in-6.8.2-SNAPSHOT.pom
     Required by:
         project :app

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:mapDebugSourceSetPaths'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.braintreepayments.api:drop-in:6.8.2-SNAPSHOT.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/maven-metadata.xml
       - https://dl.google.com/dl/android/maven2/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/drop-in-6.8.2-SNAPSHOT.pom
       - https://repo.maven.apache.org/maven2/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/maven-metadata.xml
       - https://repo.maven.apache.org/maven2/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/drop-in-6.8.2-SNAPSHOT.pom
       - https://jitpack.io/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/maven-metadata.xml
       - https://jitpack.io/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/drop-in-6.8.2-SNAPSHOT.pom
       - https://cardinalcommerceprod.jfrog.io/artifactory/android/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/maven-metadata.xml
       - https://cardinalcommerceprod.jfrog.io/artifactory/android/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/drop-in-6.8.2-SNAPSHOT.pom
     Required by:
         project :app
   > Could not find com.braintreepayments.api:drop-in:6.8.2-SNAPSHOT.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/maven-metadata.xml
       - https://dl.google.com/dl/android/maven2/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/drop-in-6.8.2-SNAPSHOT.pom
       - https://repo.maven.apache.org/maven2/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/maven-metadata.xml
       - https://repo.maven.apache.org/maven2/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/drop-in-6.8.2-SNAPSHOT.pom
       - https://jitpack.io/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/maven-metadata.xml
       - https://jitpack.io/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/drop-in-6.8.2-SNAPSHOT.pom
       - https://cardinalcommerceprod.jfrog.io/artifactory/android/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/maven-metadata.xml
       - https://cardinalcommerceprod.jfrog.io/artifactory/android/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/drop-in-6.8.2-SNAPSHOT.pom
     Required by:
         project :app

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

3: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:mergeDebugResources'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.braintreepayments.api:drop-in:6.8.2-SNAPSHOT.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/maven-metadata.xml
       - https://dl.google.com/dl/android/maven2/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/drop-in-6.8.2-SNAPSHOT.pom
       - https://repo.maven.apache.org/maven2/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/maven-metadata.xml
       - https://repo.maven.apache.org/maven2/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/drop-in-6.8.2-SNAPSHOT.pom
       - https://jitpack.io/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/maven-metadata.xml
       - https://jitpack.io/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/drop-in-6.8.2-SNAPSHOT.pom
       - https://cardinalcommerceprod.jfrog.io/artifactory/android/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/maven-metadata.xml
       - https://cardinalcommerceprod.jfrog.io/artifactory/android/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/drop-in-6.8.2-SNAPSHOT.pom
     Required by:
         project :app
   > Could not find com.braintreepayments.api:drop-in:6.8.2-SNAPSHOT.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/maven-metadata.xml
       - https://dl.google.com/dl/android/maven2/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/drop-in-6.8.2-SNAPSHOT.pom
       - https://repo.maven.apache.org/maven2/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/maven-metadata.xml
       - https://repo.maven.apache.org/maven2/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/drop-in-6.8.2-SNAPSHOT.pom
       - https://jitpack.io/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/maven-metadata.xml
       - https://jitpack.io/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/drop-in-6.8.2-SNAPSHOT.pom
       - https://cardinalcommerceprod.jfrog.io/artifactory/android/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/maven-metadata.xml
       - https://cardinalcommerceprod.jfrog.io/artifactory/android/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/drop-in-6.8.2-SNAPSHOT.pom
     Required by:
         project :app

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

4: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:processDebugMainManifest'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.braintreepayments.api:drop-in:6.8.2-SNAPSHOT.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/maven-metadata.xml
       - https://dl.google.com/dl/android/maven2/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/drop-in-6.8.2-SNAPSHOT.pom
       - https://repo.maven.apache.org/maven2/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/maven-metadata.xml
       - https://repo.maven.apache.org/maven2/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/drop-in-6.8.2-SNAPSHOT.pom
       - https://jitpack.io/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/maven-metadata.xml
       - https://jitpack.io/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/drop-in-6.8.2-SNAPSHOT.pom
       - https://cardinalcommerceprod.jfrog.io/artifactory/android/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/maven-metadata.xml
       - https://cardinalcommerceprod.jfrog.io/artifactory/android/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/drop-in-6.8.2-SNAPSHOT.pom
     Required by:
         project :app
   > Could not find com.braintreepayments.api:drop-in:6.8.2-SNAPSHOT.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/maven-metadata.xml
       - https://dl.google.com/dl/android/maven2/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/drop-in-6.8.2-SNAPSHOT.pom
       - https://repo.maven.apache.org/maven2/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/maven-metadata.xml
       - https://repo.maven.apache.org/maven2/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/drop-in-6.8.2-SNAPSHOT.pom
       - https://jitpack.io/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/maven-metadata.xml
       - https://jitpack.io/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/drop-in-6.8.2-SNAPSHOT.pom
       - https://cardinalcommerceprod.jfrog.io/artifactory/android/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/maven-metadata.xml
       - https://cardinalcommerceprod.jfrog.io/artifactory/android/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/drop-in-6.8.2-SNAPSHOT.pom
     Required by:
         project :app

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

5: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:mergeDebugAssets'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.braintreepayments.api:drop-in:6.8.2-SNAPSHOT.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/maven-metadata.xml
       - https://dl.google.com/dl/android/maven2/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/drop-in-6.8.2-SNAPSHOT.pom
       - https://repo.maven.apache.org/maven2/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/maven-metadata.xml
       - https://repo.maven.apache.org/maven2/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/drop-in-6.8.2-SNAPSHOT.pom
       - https://jitpack.io/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/maven-metadata.xml
       - https://jitpack.io/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/drop-in-6.8.2-SNAPSHOT.pom
       - https://cardinalcommerceprod.jfrog.io/artifactory/android/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/maven-metadata.xml
       - https://cardinalcommerceprod.jfrog.io/artifactory/android/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/drop-in-6.8.2-SNAPSHOT.pom
     Required by:
         project :app
   > Could not find com.braintreepayments.api:drop-in:6.8.2-SNAPSHOT.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/maven-metadata.xml
       - https://dl.google.com/dl/android/maven2/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/drop-in-6.8.2-SNAPSHOT.pom
       - https://repo.maven.apache.org/maven2/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/maven-metadata.xml
       - https://repo.maven.apache.org/maven2/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/drop-in-6.8.2-SNAPSHOT.pom
       - https://jitpack.io/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/maven-metadata.xml
       - https://jitpack.io/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/drop-in-6.8.2-SNAPSHOT.pom
       - https://cardinalcommerceprod.jfrog.io/artifactory/android/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/maven-metadata.xml
       - https://cardinalcommerceprod.jfrog.io/artifactory/android/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/drop-in-6.8.2-SNAPSHOT.pom
     Required by:
         project :app

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

6: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:checkDebugDuplicateClasses'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.braintreepayments.api:drop-in:6.8.2-SNAPSHOT.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/maven-metadata.xml
       - https://dl.google.com/dl/android/maven2/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/drop-in-6.8.2-SNAPSHOT.pom
       - https://repo.maven.apache.org/maven2/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/maven-metadata.xml
       - https://repo.maven.apache.org/maven2/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/drop-in-6.8.2-SNAPSHOT.pom
       - https://jitpack.io/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/maven-metadata.xml
       - https://jitpack.io/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/drop-in-6.8.2-SNAPSHOT.pom
       - https://cardinalcommerceprod.jfrog.io/artifactory/android/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/maven-metadata.xml
       - https://cardinalcommerceprod.jfrog.io/artifactory/android/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/drop-in-6.8.2-SNAPSHOT.pom
     Required by:
         project :app
   > Could not find com.braintreepayments.api:drop-in:6.8.2-SNAPSHOT.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/maven-metadata.xml
       - https://dl.google.com/dl/android/maven2/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/drop-in-6.8.2-SNAPSHOT.pom
       - https://repo.maven.apache.org/maven2/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/maven-metadata.xml
       - https://repo.maven.apache.org/maven2/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/drop-in-6.8.2-SNAPSHOT.pom
       - https://jitpack.io/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/maven-metadata.xml
       - https://jitpack.io/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/drop-in-6.8.2-SNAPSHOT.pom
       - https://cardinalcommerceprod.jfrog.io/artifactory/android/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/maven-metadata.xml
       - https://cardinalcommerceprod.jfrog.io/artifactory/android/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/drop-in-6.8.2-SNAPSHOT.pom
     Required by:
         project :app

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

7: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:desugarDebugFileDependencies'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.braintreepayments.api:drop-in:6.8.2-SNAPSHOT.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/maven-metadata.xml
       - https://dl.google.com/dl/android/maven2/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/drop-in-6.8.2-SNAPSHOT.pom
       - https://repo.maven.apache.org/maven2/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/maven-metadata.xml
       - https://repo.maven.apache.org/maven2/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/drop-in-6.8.2-SNAPSHOT.pom
       - https://jitpack.io/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/maven-metadata.xml
       - https://jitpack.io/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/drop-in-6.8.2-SNAPSHOT.pom
       - https://cardinalcommerceprod.jfrog.io/artifactory/android/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/maven-metadata.xml
       - https://cardinalcommerceprod.jfrog.io/artifactory/android/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/drop-in-6.8.2-SNAPSHOT.pom
     Required by:
         project :app
   > Could not find com.braintreepayments.api:drop-in:6.8.2-SNAPSHOT.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/maven-metadata.xml
       - https://dl.google.com/dl/android/maven2/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/drop-in-6.8.2-SNAPSHOT.pom
       - https://repo.maven.apache.org/maven2/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/maven-metadata.xml
       - https://repo.maven.apache.org/maven2/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/drop-in-6.8.2-SNAPSHOT.pom
       - https://jitpack.io/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/maven-metadata.xml
       - https://jitpack.io/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/drop-in-6.8.2-SNAPSHOT.pom
       - https://cardinalcommerceprod.jfrog.io/artifactory/android/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/maven-metadata.xml
       - https://cardinalcommerceprod.jfrog.io/artifactory/android/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/drop-in-6.8.2-SNAPSHOT.pom
     Required by:
         project :app

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

8: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:mergeDebugNativeLibs'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.braintreepayments.api:drop-in:6.8.2-SNAPSHOT.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/maven-metadata.xml
       - https://dl.google.com/dl/android/maven2/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/drop-in-6.8.2-SNAPSHOT.pom
       - https://repo.maven.apache.org/maven2/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/maven-metadata.xml
       - https://repo.maven.apache.org/maven2/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/drop-in-6.8.2-SNAPSHOT.pom
       - https://jitpack.io/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/maven-metadata.xml
       - https://jitpack.io/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/drop-in-6.8.2-SNAPSHOT.pom
       - https://cardinalcommerceprod.jfrog.io/artifactory/android/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/maven-metadata.xml
       - https://cardinalcommerceprod.jfrog.io/artifactory/android/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/drop-in-6.8.2-SNAPSHOT.pom
     Required by:
         project :app
   > Could not find com.braintreepayments.api:drop-in:6.8.2-SNAPSHOT.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/maven-metadata.xml
       - https://dl.google.com/dl/android/maven2/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/drop-in-6.8.2-SNAPSHOT.pom
       - https://repo.maven.apache.org/maven2/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/maven-metadata.xml
       - https://repo.maven.apache.org/maven2/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/drop-in-6.8.2-SNAPSHOT.pom
       - https://jitpack.io/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/maven-metadata.xml
       - https://jitpack.io/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/drop-in-6.8.2-SNAPSHOT.pom
       - https://cardinalcommerceprod.jfrog.io/artifactory/android/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/maven-metadata.xml
       - https://cardinalcommerceprod.jfrog.io/artifactory/android/com/braintreepayments/api/drop-in/6.8.2-SNAPSHOT/drop-in-6.8.2-SNAPSHOT.pom
     Required by:
         project :app

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
22 actionable tasks: 21 executed, 1 up-to-date

**Comment by sshropshire** [comment]
Hello, please follow the [issue template](https://github.com/braintree/braintree-android-drop-in/issues/new?assignees=&labels=&template=bug_report.md) when filing a bug with the SDK.
