### ISSUE TITLE
DropInActivity remains in progress state upon leaving ThreeDSecureWebViewActivity 

### ISSUE THREAD

**Issue by consp1racy** [braintree/braintree-android-drop-in#41]
### General information

* SDK/Library version: drop-in:3.0.8, braintree:2.5.2, card-form:3.0.6
* Environment: Any
* Android Version and Device: Any

### Issue description

When leaving ThreeDSecureWebViewActivity using the system back button or action bar up button underlying Drop-In activity is left in progress state.

### Expected behavior

Upon leaving ThreeDSecureWebViewActivity Drop-In activity would hide progress and show the list of recent and availabel payment methods again.

**Comment by lkorth** [comment]
Thanks for the report @consp1racy. I just opened #43 to fix this.
