### ISSUE TITLE
3DSecure web page reloads with "SESSION EXPIRED" message after any action

### ISSUE THREAD

**Issue by consp1racy** [braintree/braintree-android-drop-in#42]
### General information

* SDK/Library version: drop-in:3.0.8, braintree:2.5.2, card-form:3.0.6
* Environment: Production
* Android Version and Device: Any

### Issue description

3D secure requested by drop-in correctly opens, SMS arrives, but when either of Cancel or Submit buttons is clicked the page switches to a "SESSION EXPIRED" page instead of canceling or failure or success.

The card issuer is mBank CZ. I tried cards from two major associations issued by the same bank, both presented with this issue.

**Comment by consp1racy** [comment]
Fixed by using braintree 2.5.4.

>## 2.5.4
>* Accept third party cookies in ThreeDSecureWebView for Lollipop and above

https://github.com/braintree/braintree_android/blob/master/CHANGELOG.md

**Comment by ignasbagdonas** [comment]
Hello, I have the same issue now with this bank with latest braintree sdk.
