### ISSUE TITLE
Get reject by google play due to violation of User Data policy

### ISSUE THREAD

**Issue by LouisLin0706** [braintree/braintree-android-drop-in#428]
### Braintree SDK Version

6.7.0

### Environment

Production

### Android Version & Device

Google play review 

### Braintree dependencies

N / A

### Describe the bug

App being reject by google play due to : Violation of User Data policy

We reviewed SDKs used by your app and found noncompliant version(s) of SDK(s) which collects persistent device identifiers. Persistent device identifiers may not be linked to other personal and sensitive user data or resettable device identifiers.

Issue details

We found an issue in the following area(s):

SPLIT_BUNDLE 102: :
**SDK: Braintree Payments com.braintreepayments.api:data-collector (consider upgrading to version 4.31.0)** 

It didn't work when the version increase to 6.11.0 

### To reproduce

N/A

### Expected behavior

Should be able to pass the review from google play.

### Screenshots

<img width="965" alt="Screen Shot 2023-08-17 at 9 11 40 PM" src="https://github.com/braintree/braintree-android-drop-in/assets/11386794/e3098829-bc57-454d-ad30-364ac40f1c37">

**Comment by sshropshire** [comment]
Hi @LouisLin0706 thanks for using the Braintree SDK for Android. You'll have to update to the latest [6.11.0](https://github.com/braintree/braintree-android-drop-in/blob/master/CHANGELOG.md#6110) version and make sure that all of your build tracks (e.g. open, closed, internal testing) are up to date. The issue should clear up after all tracks point to the latest version of DropIn. Closing this now.
