### ISSUE TITLE
Paypal payments end with 'User cancelled dropin'

### ISSUE THREAD

**Issue by emafru90** [braintree/braintree-android-drop-in#444]
### Braintree SDK Version

4.38.2

### Environment

Production

### Android Version & Device

Android 12 Pixel 12 -  Android 13 Realme 8 pro

### Braintree dependencies

'com.braintreepayments.api:drop-in:6.13.0'

### Describe the bug

Every time user try payment with paypal, after payment, on return in app screen,  sdk return following error 'User canceled DropIn.' This is a custom native plugin integrate in react native app.
In screenshots I've add error detail and part of androidManifest of React native app.

braintreeDeepLinkReturnUrlScheme is right filled.

This process works fine in sandbox environment 

### To reproduce

1. Init braintree dropin
2. Show payments list
3. Select Paypal
4. Go to Paypal screen
5. Insert right credential
6. Go back in app
7. User get 'User canceled DropIn.'

### Expected behavior

We expect to get right failure message or success message

### Screenshots

![Screenshot 2023-09-29 alle 09 49 48](https://github.com/braintree/braintree-android-drop-in/assets/146420545/c04f705b-0b68-481e-b538-42f4ed7a2274)
![Screenshot 2023-09-29 alle 09 55 44](https://github.com/braintree/braintree-android-drop-in/assets/146420545/6cb45c97-191b-496f-87b9-fcd5b3128155)

**Comment by sshropshire** [comment]
Hi @emafru90 thanks for using the Braintree SDK for Android. Does your application id happen to have uppercase letters?

**Comment by emafru90** [comment]
Hi @sshropshire thansk for yout feedback, I solved it by removing intent-filter from android manifest. Thank you.

**Comment by sshropshire** [comment]
@emafru90 awesome!
