### ISSUE TITLE
Cardinal SDK configure Error

### ISSUE THREAD

**Issue by fradev94** [braintree/braintree-android-drop-in#447]
### Braintree SDK Version

6.13.0

### Environment

Production

### Android Version & Device

Android 14

### Braintree dependencies

'com.braintreepayments.api:drop-in:6.13.0'

### Describe the bug

Some users with Android 14 devices have obtained an error during a Braintree recharge. In particular after having selected a card the onActivityResult() returns this exception: resultCode = 1, exception.getMessage() = Cardinal SDK configure Error.

### To reproduce

Try to recharge with a card

### Expected behavior

The expected behavior is that the recharge is successfully executed.

**Comment by sshropshire** [comment]
Hey @fradev94 thanks for using the Braintree SDK for Android. Are you able to reproduce this issue by any chance?

Also we throw this exception in response to an exception thrown by the Cardinal SDK. If we could get information on what the exception's `getCause()` method returns, that will give us the original exception from Cardinal.

**Comment by hollabaq86** [comment]
Going to close this since we haven't heard back from OP. If folks do retrieve Cardinal's exception message for us, please create a new issue with those details.
