### ISSUE TITLE
Upgrade braintree_android to 4.41.0 

### ISSUE THREAD

**Issue by mionescu95** [braintree/braintree-android-drop-in#462]
### Is your feature request related to a problem? Please describe.

Hi, we received emails from Google Play regarding 
SDK: Paypal Data Collector com.paypal.android.sdk:data-collector (consider upgrading to version com.braintreepayments.api:data-collector:3.21.0)

### Describe the solution you'd like.

We saw that braintree_android already solved this issue in the latest release. Do you plan to update this library soon and create a new release ?

**Comment by sshropshire** [comment]
Hi @mionescu95 can you confirm which version of DropIn you're using at the moment?

**Comment by sshropshire** [comment]
@mionescu95 you'll need version `3.21.1` to ensure compliance.

**Comment by mionescu95** [comment]
Hi @sshropshire 
We are implementing com.braintreepayments.api:drop-in:6.11.1, not directly com.braintreepayments.api:data-collector

**Comment by mionescu95** [comment]
Thanks for the quick response @sshropshire. I just want to double confirm that 6.14.0 would solve the issue before going to release because I saw that braintree_android fixes it in [4.41.0](https://github.com/braintree/braintree_android/releases/tag/4.41.0) and drop-in 6.14.0 implements braintree_android 4.40.1, so not exactly the version we need.

**Comment by sshropshire** [comment]
@mionescu95 oh understood. Yes we do need to bump our DropIn version you're correct.

But in your case updating to the latest DropIn version should be fine. The `4.41.0` Core SDK version addresses an issue with the `:PayPalNativeCheckout` module, which DropIn does not use.
