### ISSUE TITLE
Updating outdated MasterCard logo

### ISSUE THREAD

**Issue by mrsasha** [braintree/braintree-android-drop-in#47]
Hi,

I noticed that you're still using the old MasterCard logo, which got changed last year. Can we get this updated please?

http://www.underconsideration.com/brandnew/archives/new_logo_and_identity_for_mastercard_by_pentagram.php
https://brand.mastercard.com/brandcenter/mastercard-brand-mark.html

Thanks!

**Comment by lkorth** [comment]
Duplicate of braintree/android-card-form#34

**Comment by lkorth** [comment]
Vaulted logos were updated in f48353f44dbda577877c0db95109d6b8d47aab43 and 0bf0fc1fa40bbf30a50330ca9e29eafaacba09d0
