### ISSUE TITLE
about fetch last payment method customer_id 

### ISSUE THREAD

**Issue by avalond** [braintree/braintree-android-drop-in#48]
### General information

* SDK/Library version: drop-in:3.1.0
* Environment: sanbox
* Android Version and Device: 6.0.1 nexus 5

### Issue description
Fetch last used payment method in sanbox environment,I do not know how to set up customer_id and then let him work，the backend node.js doc  is not told me how to set this, please  help thanks

**Comment by bluk** [comment]
Please see the [Customers documentation](https://developers.braintreepayments.com/guides/customers/node) on the Braintree Developer website. You can create a customer using the Node.js SDK and associate payment methods at creation time or through an update.

When [generating the client token](https://developers.braintreepayments.com/reference/request/client-token/generate/node#specify-a-customer-id), you can specify a customer ID. The client token will then be associated with a customer ID which you can use to initialize drop-in with. If you still have a question, please leave a comment or open a new issue. Thanks.
