### ISSUE TITLE
Google Payments API support

### ISSUE THREAD

**Issue by mrsasha** [braintree/braintree-android-drop-in#49]
Hi,

wanted to ask about the Google Payments API support - I've seen some commits in the android library that should enable it, but are you also replacing the "Pay with Android Pay" with "Pay with Google" on the UI side?

Also, will there be a new drop-in release with Google Payments support soon?

Thanks!

**Comment by sdcoffey** [comment]
Hey @mrsasha,

Thanks for bringing this to our attention, and sorry we've left this issue languishing for so long. We're working on updating the assets in drop-in to reflect the new branding. We don't have an ETA for this but it's on the roadmap, and we'll update you here when we've made progress.

**Comment by mrsasha** [comment]
Hey @sdcoffey, thanks for the update, I appreciate it! I was just noticing that on your website, everything has already been replaced with "Pay with Google", so the marketing department is eager for this, I think. :)

**Comment by sdcoffey** [comment]
Hey @mrsasha,

Just merged these changes, we'll be releasing shortly.
