### ISSUE TITLE
Skip 'Select Payment Method' modal when only one payment method enabled

### ISSUE THREAD

**Issue by hankyjcheng** [braintree/braintree-android-drop-in#491]
### Is your feature request related to a problem? Please describe.

If we're only supporting a single type of payment method such as Credit or Debit Card, it feels redundant if users have to click the only option available on 'Select Payment Method' modal. 
![Screenshot_20241118-171914](https://github.com/user-attachments/assets/259e2318-2e62-4b84-b2c7-16354e6170b7)

### Describe the solution you'd like.

Ability to skip the 'Select Payment Method' modal if there are only one payment method enabled to the users.

**Comment by richherrera** [comment]
Thank you for the feedback! I see the value in the idea and agree with its core concept. However, implementing it could lead to a disruptive experience for users if additional payment methods are introduced later. If you’re supporting a single payment type, I recommend our [SDK](https://github.com/braintree/braintree_android), which supports card (credit/debit) payments.
