### ISSUE TITLE
Failed to add com.braintreepayments.api:drop-in:3.+ in Android App

### ISSUE THREAD

**Issue by akshaykumar0291** [braintree/braintree-android-drop-in#51]
### General information

* SDK/Library version: com.braintreepayments.api:drop-in:3.+
* Environment: Sandbox
* Android Version and Device: 26.+

### Issue description
Hi, I am trying to add com.braintreepayments.api:drop-in:3.+ in my Android Application but whenever i am adding this dependency to my app it's throwing an error like 
Failed to resolve:com.android.support:design:26.0.0
Failed to resolve:com.android.support:cardview-v7:26.0.0

Even also i am adding these dependencies to my app, the issue persist.

**Comment by sdcoffey** [comment]
Hey @akshaykumar0291,

Just following up to see if this issue has been resolved for you. It sounds like you may need update your Android SDK. Check out [the Android docs on updating your SDK via the SDK manager](https://developer.android.com/studio/intro/update.html#sdk-manager) if you're still having trouble.

**Comment by Ksoft-Technologies** [comment]
Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Could not resolve com.braintreepayments.api:braintree:2.6.0. Open File Show Details

**Comment by crookedneighbor** [comment]
Since we haven't gotten a response, I'm going to close this. 

@Ksoft-Technologies if you're still having trouble, please open a new issue with more details.
