### ISSUE TITLE
Demo App Always Says "Postal code is invalid"

### ISSUE THREAD

**Issue by jmkwok** [braintree/braintree-android-drop-in#54]
### General information

* SDK/Library version: 3.1.1-SNAPSHOT
* Environment: Sandbox
* Android Version and Device: OnePlus 3T running 7.1.1

### Issue description

When running the demo app (built off of cloning this repo) and trying to add a new credit card, no matter what the postal code is it'll always say the postal code is invalid. I have tried with 10+ different credit cards and a bunch of variations of postal codes but nothing works.

**Comment by sdcoffey** [comment]
Hey @jmkwok,

Thanks for submitting this issue. Can you share a screenshot of where you're seeing this issue, as well as some some of the failing combinations of CC number and postal code? If you haven't already seen it, check out the section in our docs about [test numbers in sandbox](https://developers.braintreepayments.com/reference/general/testing/ruby#no-credit-card-errors).

**Comment by fmontano** [comment]
@jmkwok   Try using `11111` as postal code

**Comment by crookedneighbor** [comment]
@jmkwok Since we haven't heard back from you, I'm going to close this issue, but feel free to comment here if you need further assistance.

**Comment by Yvonne1601Cai** [comment]
same issue. tried 11111, not working

**Comment by SudalaikasiRathinam** [comment]
It works with below details
Card number 4111 1111 1111 1111
CVV 400
Postal code 40000

**Comment by sestevens** [comment]
@SudalaikasiRathinam Are you seeing "Postal code is invalid" with the details you provided? If so, which version of `braintree-android-drop-in` are you using?

**Comment by strajky5** [comment]
I have same issue but in my app.
If I tested your demo application it works. 
I copy same code to my app and it's not working. 
Everytime shows "Postal code is invalid".

Tested it on Goole Pixel 2XL, Android 10
Android target and compile sdk version: 29
Included libraries:
        implementation 'com.braintreepayments.api:drop-in:4.5.0'
        implementation 'io.card:android-sdk:5.+'

I tried a bunch of options but without success.

![IMG_5913](https://user-images.githubusercontent.com/10131708/79474278-7cca1900-8006-11ea-9d76-c116e4cff46d.jpg)

**Comment by strajky5** [comment]
Thank you very much for quick response. Here is settings:
![bt](https://user-images.githubusercontent.com/10131708/79586240-24ac1900-80d1-11ea-9181-93f4afc90df7.png)

**Comment by scannillo** [comment]
@strajky5 Did you try unchecking the street address boxes? I would tinker with those a bit and make sure that the fields you're actually collecting match what your control panel expects.

**Comment by strajky5** [comment]
Yes, I just tried it and it works. Sorry my bad. Thank you for your cooperation
