### ISSUE TITLE
How to customize the payment screen in Drop-in UI

### ISSUE THREAD

**Issue by rranjithkumar100** [braintree/braintree-android-drop-in#55]
### General information

* SDK/Library version:  compile 'com.braintreepayments.api:drop-in:3.1.0'
* Environment: this issue in Sandbox 
* Android Version and Device: 5.1 & 7.0

### Issue description

Please check the version 1 customization screen. I need to customize like this

https://developers.braintreepayments.com/guides/drop-in/customization/android/v1

**_Sample customization code_** 
```
Customization customization = new Customization.CustomizationBuilder()
  .primaryDescription("Cart")
  .secondaryDescription("3 Items")
  .amount("$35")
  .submitButtonText("Purchase")
  .build();

```
But unfortunately Customization class not available in latest version. 

My Question **how to customize the  Drop-in UI payment screen in latest version library?**

**Comment by quinnjn** [comment]
We chose to remove summary portion in Drop-in 3+ in favor of keeping Drop-in more of the payment selection UI for the customer.

If you want to continue to show the merchant a cart summary, you could create your own `CartSummaryActivity` that calls Drop-in on some confirmation button.

**Comment by rranjithkumar100** [comment]
@quinnjn We moved to next payment gateway. Because we want customize UI. We waiting one month. Sadly no supports from braintree developers so we decided to move another gateway. thanks for your reply after 2 months. pls close this issue
