### ISSUE TITLE
AddCardActivity expiration date EditText disappear when focus changes

### ISSUE THREAD

**Issue by Fondesa** [braintree/braintree-android-drop-in#6]
Lib version: 3.0.1
SDK version: 24
Device model: Nexus 5X

I tried to use `AddCardActivity` with only mandatory fields (credit card number and expiration date). If I insert a valid credit card's number, when I reach the end of the line on `CardEditText`, the focus passes to `ExpirationDateEditText`.  If I focus `CardEditText` again, `ExpirationDateEditText` disappears. I have to delete at least a digit of the previously inserted credit card's number and insert it again to show `ExpirationDateEditText` again.

**Comment by quinnjn** [comment]
@Fondesa thank you for the report, and sorry for the delay!

We'll work on a fix for this flow. In the meantime you can progress by using the keyboard's next button:

![changing-card-number](https://cloud.githubusercontent.com/assets/1859215/20902605/a7b925ee-baec-11e6-9d3e-7ef9433f93de.gif)

**Comment by quinnjn** [comment]
Both the keyboard next, and the next button on screen will continue to the expiration field. I think this is acceptable since we don't want to auto advance the customer if they're editing the field.

**Comment by quinnjn** [comment]
I'm going to close this since this flow feels fine in Drop-in. If you have more concerns about this issue please reopen it.

Thanks!

**Comment by Fondesa** [comment]
Thanks very much for the explanations!
