### ISSUE TITLE
Allow Credit Card Filtering - Feature Request

### ISSUE THREAD

**Issue by sdoward** [braintree/braintree-android-drop-in#60]
In the project I work on we have a requirement to not accept Maestro cards. Would it be possible to disable particular cards in the same way we can disable Android pay in the DropInRequest?

I am happy to open a PR with the changes if you accept the feature request and you don't have the bandwidth at the moment.

**Comment by crookedneighbor** [comment]
Drop-in should automatically prevent tokenization from card types not supported by the merchant account:

https://github.com/braintree/braintree-android-drop-in/blob/85bce2a73ccb447e1704e0a104aa4e68345ad3d5/Drop-In/src/main/java/com/braintreepayments/api/dropin/view/AddCardView.java#L88
https://github.com/braintree/braintree-ios-drop-in/blob/e244a775683308f2b8da3489172017082ed20a10/BraintreeDropIn/BTCardFormViewController.m#L738

If you need Maestro cards disabled on your account, you can reach out to our support team here: https://articles.braintreepayments.com/forms/contact

**Comment by crookedneighbor** [comment]
I'm going to close this, because I think this meets the need you were looking for. Feel free to comment if you have questions.
