### ISSUE TITLE
Expedite payment method selection with only one option

### ISSUE THREAD

**Issue by kelvinleague** [braintree/braintree-android-drop-in#61]
General information
SDK/Library version: 3.+
Environment: Production
Android Version and Device: Nexus 5X

Issue description
Not a serious issue, but if the user only has a single payment method available, it should be set by default and forward the user to the payment page instead of having them select the method. This is also the case on iOS

**Comment by sdcoffey** [comment]
Hey @kelvinleague,

Thanks for the feedback! I agree with the basic principle of the idea. If we did this, however, it would create a jarring user experience for the user in the case where another payment method becomes available. If a merchant decides to start supporting Google Pay, for instance, the user would suddenly be presented with the payment sheet for the first time when they previously hadn't seen it. Additionally, this is a breaking change from a behavioral standpoint.

In any case, thanks again for the feedback, please let us know if there are any other ways we can improve the Drop-in experience.
