### ISSUE TITLE
DropinUI 3DSecure not redirecting back to app post authentication

### ISSUE THREAD

**Issue by buntydey** [braintree/braintree-android-drop-in#68]
### General information

* SDK/Library version: 27
* Environment: Sandbox
* Android Version and Device: Xiaomi, Asus

### Issue description

I have implemented DropinUI in my app with 3DSecure enabled. For credit cards that are having 3DSecure verifications, the 3DSecure page opens up in a browser. Upon hitting submit, I am shown a page with the message "If you are not redirected back to the app, tap the button to return". Everything is working fine when I tap the button and I get the 3Dnonce. But, how do I make the redirect happen automatically, instead of manual click of the button? 
On a similar note, when I am clicking on Paypal in DropinUI, it is successfully redirecting back to the app upon authentication.

**AndroidManifest**:
```
<activity android:name="com.braintreepayments.api.BraintreeBrowserSwitchActivity"
            android:launchMode="singleTask">
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="${applicationId}.braintree" />
            </intent-filter>
        </activity>
```

**DropinUI Initialization**:
```
val dropInRequest = DropInRequest()
                .clientToken(BTclientToken)
                .amount("10.00")
                .collectDeviceData(true)
                .requestThreeDSecureVerification(true)
```

**Comment by demerino** [comment]
@buntydey The root issue seems to be a change in Android API 27 that has broken the automatic redirect. It should still be automatically redirecting on API 26 and lower. We're looking into solutions and working on an update to the design that should make it clearer to users if they are not automatically redirected.

**Comment by buntydey** [comment]
Thanks. Do you have any target date for this fix?

**Comment by demerino** [comment]
`3.4.0` should have clearer instructions during the app switch while we look into a better solution.

**Comment by crookedneighbor** [comment]
Looks like there simply isn't a way to do the automatic redirect at this time. Going to close for now, but we'll continue to watch for updates that will allow us to do the redirect.
