### ISSUE TITLE
Google pay in Dropin UI

### ISSUE THREAD

**Issue by haris15** [braintree/braintree-android-drop-in#76]
General information
SDK/Library version: 27
Environment: Sandbox
Android Version and Device: Motorola 7.11

how can i test my google pay transaction using drop-in ui ?

there is no support to test transaction using test card.

**Comment by quinnjn** [comment]
Hi @haris15 

Our [Google Pay - Testing and Go Live](https://developers.braintreepayments.com/guides/google-pay/testing-go-live/android/v2) section of the developer docs can explain this better.

Unfortunately this is a limitation on the Google Pay wallet itself and not Braintree or Drop-in UI. Google Pay can only accept actual cards in their wallets. 

You can still test transactions in sandbox using a real card. The payment method nonce returned from Google Pay will be a testing payment method and not reflect the card in the Google Pay wallet.

**Comment by kamran-nazir** [comment]
> Hi @haris15
> 
> Our [Google Pay - Testing and Go Live](https://developers.braintreepayments.com/guides/google-pay/testing-go-live/android/v2) section of the developer docs can explain this better.
> 
> Unfortunately this is a limitation on the Google Pay wallet itself and not Braintree or Drop-in UI. Google Pay can only accept actual cards in their wallets.
> 
> You can still test transactions in sandbox using a real card. The payment method nonce returned from Google Pay will be a testing payment method and not reflect the card in the Google Pay wallet.

How can we call "requestPaymentMethod" for google pay using "braintree-web-drop-in" to receive payload nonce. 
Dropping my code which i am using for rendering the google pay button. after entering the card info, nothing happens when i click on "continue" button. I need payment nonce so i can send it to server for further processing.

   //My sample code
    const initializeBraintree = () => dropin.create({
                authorization: clientToken,
                container: '#dropin-container',
                googlePay: {
                    environment: "TEST",
                    googlePayVersion: 2,
                    transactionInfo: {
                        totalPriceStatus: 'FINAL',
                        totalPrice: '1',
                        currencyCode: 'USD'
                    },
                    allowedPaymentMethods: [{
                        type: 'CARD',
                        parameters: {
                            billingAddressRequired: true,
                            billingAddressParameters: {
                                format: 'FULL'
                            }
                        }
                    }],
                },
            }
                , function (error, instance) {
                    if (error)
                        console.error(error)
                    else {
                        setBraintreeInstance(instance);
                    }
                });
