### ISSUE TITLE
textColorError - SDK 28

### ISSUE THREAD

**Issue by StefanDeBruijn** [braintree/braintree-android-drop-in#77]
The use of `textColorError` in the style `bt_add_card_activity_theme` blocks users from building with SDK and support library 28

**Comment by quinnjn** [comment]
Confirmed, thanks for the report!

We are working on upgrading Braintree Android in preparation for Android P: https://github.com/braintree/braintree_android/issues/210

After we're done upgrading Braintree Android, Drop-in will also get an Android P update.

**Comment by StefanDeBruijn** [comment]
Alright, great to hear. Thanks

**Comment by quinnjn** [comment]
We can keep this issue open until it is fixed

**Comment by Klingefjord** [comment]
@dschuermann Could you clarify this workaround? Doesn't seem to work for me - what level do you declare foo in in attrs.xml and styles.xml?

**Comment by quinnjn** [comment]
I merged in #93 which solves the problem and published a [snapshot version](https://oss.sonatype.org/content/repositories/snapshots/com/braintreepayments/api/drop-in/3.6.2-SNAPSHOT/).

Please try it out and let us know if it resolves the issue!

**Comment by Klingefjord** [comment]
@quinnjin resolved the issue, thanks! 
Any estimate when this will be out in a proper release?

**Comment by quinnjn** [comment]
Glad it worked! We're working on tying up one last feature before the next release. It will be out by EOD tomorrow.

**Comment by quinnjn** [comment]
[3.7.0](https://github.com/braintree/braintree-android-drop-in/releases/tag/3.7.0) is now available.

```
implementation 'com.braintreepayments.api:drop-in:3.7.0'
```

**Comment by git-yourdevexpert** [comment]
when i add it in build.gradle file it gives error 

  implementation 'com.braintreepayments.api:drop-in:3.7.0'

error: style attribute 'attr/colorError (aka com.kudos.diplomakids:attr/colorError)' not found.
  error: failed linking references.

**Comment by Manaspaul623** [comment]
> This fix is now released and available in [3.7.0](https://github.com/braintree/braintree-android-drop-in/releases/tag/3.7.0).
> 
> ```
> implementation 'com.braintreepayments.api:drop-in:3.7.0'
> ```

Worked for me

**Comment by jjmcgarry90** [comment]
Still having this issue

**Comment by exaland** [comment]
> This fix is now released and available in [3.7.0](https://github.com/braintree/braintree-android-drop-in/releases/tag/3.7.0).
> 
> ```
> implementation 'com.braintreepayments.api:drop-in:3.7.0'
> ```

Good Method resolution :)

**Comment by dennismuturia** [comment]
> This fix is now released and available in [3.7.0](https://github.com/braintree/braintree-android-drop-in/releases/tag/3.7.0).
> 
> ```
> implementation 'com.braintreepayments.api:drop-in:3.7.0'
> ```

This worked perfectly.
