### ISSUE TITLE
The expiration date picker in Drop-in UI is sometimes full screen

### ISSUE THREAD

**Issue by Nonepse** [braintree/braintree-android-drop-in#80]
### General information

* SDK/Library version: 3.4.0
* Environment: Production?
* Android Version and Device: OxygenOS 5.1.3 - OnePlus 5T

### Issue description

Unfortunately I have no idea how to reproduce that consistently, but I have noticed a few times that the expiration date picker can expand too much and take the entire screen.
Since I can't take screenshots on this screen because of security measures, I took a short video: https://www.youtube.com/watch?v=oTRB16w_Tag

**Comment by quinnjn** [comment]
This is my new favorite Android Drop-in bug! Thank you very much for finding all these bugs. We'll take a deeper look at fixing these.

**Comment by sarahkoop** [comment]
Hi @Nonepse - The expiration date picker has been replaced with a numerical keyboard in `v5.0.0`. Please let us know if this issue persists after upgrading.
