### ISSUE TITLE
Keyboard doesn't appear for card number field when expiration date field was in focus

### ISSUE THREAD

**Issue by Nonepse** [braintree/braintree-android-drop-in#81]
### General information

* SDK/Library version: 3.4.0
* Environment: Production?
* Android Version and Device: OxygenOS 5.1.3 - OnePlus 5T

### Issue description

**Steps to reproduce:**
1. Focus the Expiration Date field
2. Click on the Card Number field
3. The numerical keyboard doesn't appear
4. Click again on Card Number field
5. The keyboard appears

Also, since the Card Number field is already properly populated, the rest of the form shouldn't disappear.

The issue doesn't appear for the CCV and Postal Code fields.

Demo: https://www.youtube.com/watch?v=iu6nRScNp2o

**Comment by quinnjn** [comment]
Great find! We'll take a look at this soon!

**Comment by sarahkoop** [comment]
Hi @Nonepse - The expiration date picker has been replaced with a numerical keyboard in `v5.0.0`. Please let us know if this issue persists after upgrading.
