### ISSUE TITLE
Expiration Date can have a numerical keyboard instead of the custom one

### ISSUE THREAD

**Issue by Nonepse** [braintree/braintree-android-drop-in#82]
### General information

* SDK/Library version: 3.4.0
* Environment: Production?
* Android Version and Device: OxygenOS 5.1.3 - OnePlus 5T

### Issue description

**Steps to reproduce:**
1. Focus on the Expiration Date field
2. Put the app in background
3. Re-open the app from the multi-task screen
4. Click on the Activity background
5. The custom date picker disappears and a numerical keyboard appears

I allows the user the enter invalid input like 5555 for the year.
Demo: https://www.youtube.com/watch?v=UHTs-S6yBXU

**NB:** Not sure if it is worth opening an issue, but shouldn't the custom date picker be white by default?
In the iOS SDK there are white and black themes, don't know if you implemented the same for Android?

**NB.2:** Sorry if technical terms are incorrects, I am an iOS dev, not Android.

**Comment by quinnjn** [comment]
Thanks for the report! We'll take a deeper look soon.

**Comment by sarahkoop** [comment]
Hi @Nonepse - The expiration date picker has been replaced with a numerical keyboard in `v5.0.0`. Please let us know if this issue persists after upgrading.
