### ISSUE TITLE
Save payment method using Google Pay on Android

### ISSUE THREAD

**Issue by trieulh-gotitapp** [braintree/braintree-android-drop-in#86]
### Issue description

Is there any ways to save the payment method using Google Pay for the next transactions? I integrated Google Pay but each time I show up Drop In, I have to choose Google Pay again. It's not default.

Thanks.

**Comment by crookedneighbor** [comment]
Google Pay _can_ be vaulted on the server side for use with recurring billing or split shipment transactions, but other than that Google requires consent from the customer for each transaction. See https://developers.braintreepayments.com/guides/google-pay/server-side/php#vaulting-google-pay for more details.
