### ISSUE TITLE
Manage vaulted payment method

### ISSUE THREAD

**Issue by bethucbg** [braintree/braintree-android-drop-in#87]
now on IOS have option "vaultManager", that option allow remove saved payment method. 
So when this function available on android ?

**Comment by crookedneighbor** [comment]
We're waiting on translations being finalized. See https://github.com/braintree/braintree-android-drop-in/pull/84

**Comment by quinnjn** [comment]
@bethucbg we've just released 3.6.0 which has vault manager / vault payment method management!

Add it to your app with:
```
implementation 'com.braintreepayments.api:drop-in:3.6.0'
```
