### ISSUE TITLE
Alternatives for BraintreePaymentActivity and PaymentRequest because it was already deprecated. 

### ISSUE THREAD

**Issue by ekahannah** [braintree/braintree-android-drop-in#89]
### General information

* SDK/Library version:  3.5.2
* Environment:  Production
* Android Version and Device: 

### Issue description

I upgraded the Braintree drop in from 2.0 to 3.5.2. However, when I try to build it, there are other classes that were already deprecated. They are BraintreePaymentActivity and PaymentRequest.

I am using them in my code, may I know if there are alternative classes to this? 

I am using BraintreePaymentActivity for:
BraintreePaymentActivity.EXTRA_PAYMENT_METHOD_NONCE); BraintreePaymentActivity.BRAINTREE_RESULT_DEVELOPER_ERROR
BraintreePaymentActivity.BRAINTREE_RESULT_SERVER_ERROR
BraintreePaymentActivity.BRAINTREE_RESULT_SERVER_UNAVAILABLE

PaymentRequest for:
new PaymentRequest()
                .clientToken(clientToken)
                .amount(currencyAndAmount)
                .primaryDescription(primaryDescription)
                .secondaryDescription(secondaryDescription)
                .submitButtonText(submitButtonText)
                .defaultFirst(true);

paymentRequest.getIntent(this), PAYMENT_REQUEST_CODE);

**Comment by quinnjn** [comment]
We don't currently have an upgrade guide from 2 to 3 but I can give you some details that should help with your upgrade.

# Launching Drop-in

In version 2 you used `PaymentRequest` to setup the Drop-in request. In version 3 it is now called `DropInRequest`. The equivalent code would be the following:

```
DropInRequest dropInRequest = new DropInRequest()
    .clientToken(clientToken)
    .amount(currencyAndAmount);

startActivityForResult(dropInRequest.getIntent(context), PAYMENT_REQUEST_CODE); 
```

Note that `primaryDescription`, `secondaryDescription`, and `submitButtonText` are no longer available. We no longer display descriptions in Drop-in. There is no longer a "submit" button in Drop-in, once the customer has finished entering their payment method Drop-in submits automatically.

`defaultFirst` is only true in version 3 so you're fine there.

# Receiving a result
Drop-in returns results through `onActivityResult` in the activity or fragment you ran `startActivityForResult(dropInRequest.getIntent(context), ...)` from. 

You can override the `onActivityResult` to access the Drop-in result. Here is the example from [Usage in the README](https://github.com/braintree/braintree-android-drop-in#usage) with the comments modified for this explanation.

```
@Override
public void onActivityResult(int requestCode, int resultCode, Intent data) {
    super.onActivityResult(requestCode, resultCode, data);

    if (requestCode == DROP_IN_REQUEST) {
        if (resultCode == Activity.RESULT_OK) {
            DropInResult result = data.getParcelableExtra(DropInResult.EXTRA_DROP_IN_RESULT);

            // This is where you access the PaymentMethodNonce in version 3.
            String paymentMethodNonce = result.getPaymentMethodNonce().getNonce();
            // send paymentMethodNonce to your server
        } else if (resultCode == Activity.RESULT_CANCELED) { 
            // This is how you detect if the customer cancelled in version 3.
        } else {
            // This is where you get errors in version 3.
            Exception exception = (Exception) data.getSerializableExtra(DropInActivity.EXTRA_ERROR);
        }
    }
}
```

If you would like some more information there are examples on how to use version 3 Drop-in at these links:
- [Usage in the README](https://github.com/braintree/braintree-android-drop-in#usage)
- [Starting Drop-in on our developer docs](https://developers.braintreepayments.com/guides/drop-in/setup-and-integration/android/v2#starting-drop-in)
