### ISSUE TITLE
startActivityForResult calling Fragment

### ISSUE THREAD

**Issue by imran-samed** [braintree/braintree-android-drop-in#90]
I'm calling stratActivityforResult insde fragment.

* SDK/Library version:
'com.braintreepayments.api:braintree:2.+'
'com.braintreepayments.api:drop-in:3.+'

* Environment: 
SandBox

* Android Version and Device: 
Redmi 3s with 6.0

### Issue description
I'm calling stratActivityforResult insde fragment. its calling **onActivity** inside fragment first then it goes to **onActivity** of parent activity.
I just don't want to call **onActivity inside my parent activity**
here is my code..
```
void addMoney(View v, String amount) {
        DropInRequest dropInRequest = new DropInRequest()
                .clientToken(amount)
                .amount(this.amount);
        startActivityForResult(dropInRequest.getIntent(getContext()), B_REQUEST_CODE);
    }
```

**now onActivity inside a fragment**
```
@Override
    public void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        if (requestCode == B_REQUEST_CODE) {
            if (resultCode == Activity.RESULT_OK) {
                String ss = data.getStringExtra(EXTRA_PAYMENT_RESULT);
                DropInResult result = data.getParcelableExtra(DropInResult.EXTRA_DROP_IN_RESULT);
                String sss = result.getPaymentMethodNonce().getNonce();
                sendPayment(this.amount, sss);
                Log.e(TAG, "onActivityResult: RESULT_OK");
                // use the result to update your UI and send the payment method nonce to your server
            } else if (resultCode == Activity.RESULT_CANCELED) {
                Log.e(TAG, "onActivityResult: RESULT_CANCELED");
                // the user canceled
            } else {
                // handle errors here, an exception may be available in
                Exception error = (Exception) data.getSerializableExtra(DropInActivity.EXTRA_ERROR);
                Log.e(TAG, "onActivityResult: Exception" + error.getMessage());
            }
        }
    }
```

Thanks in advance.

**Comment by quinnjn** [comment]
Hi @imran-samed 

I formatted your comment so I could read the code. I don't think I fully understand your question. Are you asking how to get the Drop-in's `onActivityResult` callback in your activity? 

Whatever `Context` is passed into `DropInRequest#getIntent(Context)` will get the `onActivityResult` callback.

If you're trying to start Drop-in from a fragment:
- `dropInRequest.getIntent(getContext())` uses the **fragment**'s context, so the **fragment** `onActivityResult` will be called.
- `dropInRequest.getIntent(getActivity())` uses the fragment's **activity** context, so the **activity** `onActivityResult` will be called.

Closing this issue, feel free to comment if I did not understand your question correctly.
