### ISSUE TITLE
disable card option via drop-in parameter

### ISSUE THREAD

**Issue by darshansawe** [braintree/braintree-android-drop-in#91]
Is there a way in Android/iOS drop-in to control the visibility of card option as can be done for web drop-in using  paymentOptionPriority parameter

https://braintree.github.io/braintree-web-drop-in/docs/current/module-braintree-web-drop-in.html#.create

**Comment by crookedneighbor** [comment]
There is currently no way to do that in Android Drop-in. It's on our list of features to implement, so thanks for bringing it up!

**Comment by darshansawe** [comment]
Thanks for that update. Can you give an approximate time frame for this?

**Comment by crookedneighbor** [comment]
I don't have an approximate time frame right now. We have some other priorities we need to get through first, but if you need the functionality sooner, pull requests are welcome!
