### ISSUE TITLE
Inquiry: LineItems

### ISSUE THREAD

**Issue by Viralkanz** [braintree/braintree-android-drop-in#96]
### General information

* SDK/Library version: 3.5.2
* Environment: Sandbox 
* Android Version and Device: Android 7.0 (any)

### Issue description

I want to use 'Drop In' for "Credit Card" payment and "PayPal" express checkout. I used following code to open "WebView" for "PayPal" express checkout:

`PayPalRequest request = new PayPalRequest("0.01")
.intent(PayPalRequest.INTENT_SALE)
.userAction(PayPalRequest.USER_ACTION_COMMIT)
.landingPageType(PayPalRequest.LANDING_PAGE_TYPE_LOGIN)
.shippingAddressRequired(true)
.shippingAddressOverride(postalAddress)
.currencyCode("USD")
.displayName("John Doe")
.localeCode("US")
.billingAgreementDescription("Your agreement description");
 PayPal.requestOneTimePayment(mBraintreeFragment, request);`

Can we pass "LineItem" in it? We want to use in e-commerce API.

[My Code](https://gist.github.com/Viralkanz/cbaa4d18b23fa5518149fe0132c0aa67.js)

**Comment by crookedneighbor** [comment]
At this time, line items are only supported on the server side. See https://developers.braintreepayments.com/reference/request/transaction/sale/node#line_items

**Comment by crookedneighbor** [comment]
Feel free to contact our support team for additional help with your integration: https://articles.braintreepayments.com/forms/contact
